### ISSUE TITLE
přidělení urn:nbn příloze ročníku - nepropíše se do proarcu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#1156]
Máme verzi 3.5.13 a k vyšší se teď nedostanu - pokud to můžete prosím někdo otestovat ve vyšší verzi, udělejte to prosím, a jestli je to tam už OK, zavřete issue s informací, ve které verzi už je to opravené, díky.
Jinak popíšu náš problém. Máme periodikum s přílohami ročníku. Před exportem spustíme přidělování urn:nbn, a to běží, dokud nedojde k příloze ročníku. Resolver ji zaregistruje (příklad urn:nbn:cz:hka001-000t0a), ale nepropíše se do proarcu, ten místo toho hodí exception. 

![exception](https://user-images.githubusercontent.com/6359479/79749581-c02acd00-830f-11ea-9010-fd13c963beaa.png)

**Comment by SykoraLukas** [comment]
Když se klikne na ten řádek, kde je exception, co je v tom okně dole napsane?

**Comment by luckajirku** [comment]
java.lang.IllegalStateException: uuid:084b1fe5-2fb4-4e10-9524-37320aa456ac: Cannot write URN:NBN urn:nbn:cz:hka001-000t0f
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:725)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.processNdkPeriodicalIssue(UrnNbnVisitor.java:449)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:173)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:78)
at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:57)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:114)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:78)
at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
at cz.cas.lib.proarc.common.object.HierarchyObjectVisitor.visitChildren(HierarchyObjectVisitor.java:49)
at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visitNdkPeriodicalVolume(DefaultNdkVisitor.java:89)
at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:47)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:114)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:78)
at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnService.register(UrnNbnService.java:72)
at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.registerUrnNbn(DigitalObjectResource.java:1423)
at sun.reflect.GeneratedMethodAccessor519.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:304)
at org.apache.catalina.valves.RemoteHostValve.invoke(RemoteHostValve.java:82)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
Caused by: cz.cas.lib.proarc.common.fedora.DigitalObjectValidationException: PID: uuid:084b1fe5-2fb4-4e10-9524-37320aa456ac, dsId: BIBLIO_MODS, MODS validation
at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkBeforeWrite(NdkMetadataHandler.java:588)
at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetadataHandler.java:675)
at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadata(NdkMetadataHandler.java:140)
at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:720)
... 69 more

**Comment by luckajirku** [comment]
to je z přílohy dalšího ročníku, udělalo to to samé. jinak kdybys na to náhodou koukal do našeho proarcu, tak tam už jsou ta urn:nbn do metadat doplněná ručně, ať tě to nezmate.

**Comment by SykoraLukas** [comment]
Podle logu to vypadá na nevalidně vyplněná metadata. Když vlezeš na tu přílohu a dáš uložit, nevyběhne nějaká chybová hláška? Hádám že nesouhlasí vyplněná pole s pravidly RDA/AACR.

**Comment by luckajirku** [comment]
Tak v tuhle chvíli vyběhne už jen hláška Metadata s přiděleným URN:NBN nelze měnit!

**Comment by luckajirku** [comment]
Tak jsme se asi dopátrali. Vypadá to na problém, který už měl být vyřešený, issue je zavřené, ale stále to nefunguje jak má - issue https://github.com/proarc/proarc/issues/927. Při založení přílohy v rda periodiku se stále zakládají přílohy jako aacr a je třeba to ručně přecvaknout. Na pohled to pak vypadá OK, ale zřejmě to OK není.

**Comment by luckajirku** [comment]
Takže tamto issue znovu otevírám, je to tak, že když je titul aacr, ročník i číslo se založí automaticky aacr, kdežto příloha se založí rda. A když je titul rda, ročník i čísla se založí automaticky rda, ale příloha se založí aacr. Pokud to potom přecvakneme ručně, dělá to tyhle chyby. Nejdřív to bude chtít opravit tu 927.

**Comment by SykoraLukas** [comment]
Opraveno v #927

**Comment by hosak** [comment]
Ve verzi 3.6 stále nefunguje. 
Přidělování urn:nbn vyhodí tohle okýnko:
![urnnbn k přílohám pořád nejde](https://user-images.githubusercontent.com/19148958/89285005-eb7fc080-d64f-11ea-9457-c756c2ce6707.JPG)



Kompletní text chybové hlášky je následující:
java.lang.IllegalStateException: uuid:fe5f4b75-ba9b-4d10-a62e-6e1eefe60dcc: Cannot write URN:NBN urn:nbn:cz:hka001-000t4r
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:771)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.processNdkPeriodicalIssue(UrnNbnVisitor.java:495)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:175)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:79)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:57)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:116)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:79)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.object.HierarchyObjectVisitor.visitChildren(HierarchyObjectVisitor.java:49)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visitNdkPeriodicalVolume(DefaultNdkVisitor.java:91)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:47)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:116)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:79)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnService.register(UrnNbnService.java:72)
	at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.registerUrnNbn(DigitalObjectResource.java:1516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:304)
	at org.apache.catalina.valves.RemoteHostValve.invoke(RemoteHostValve.java:82)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cz.cas.lib.proarc.common.fedora.DigitalObjectValidationException: PID: uuid:fe5f4b75-ba9b-4d10-a62e-6e1eefe60dcc, dsId: BIBLIO_MODS, MODS validation
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkBeforeWrite(NdkMetadataHandler.java:619)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetadataHandler.java:706)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadata(NdkMetadataHandler.java:141)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:766)
	... 70 more

**Comment by luckajirku** [comment]
Kdy by mohlo být prosím tohle (a všechny související issues, které se týkají příloh) vyřešené? Opravdu to je potřeba.

**Comment by hosak** [comment]
Podle instrukcí ze včerejší schůzky jsem chtěl otestovat, jak se to chová na testovacím serveru a jestli to už je opravené. Na testovacím serveru ale není jediná příloha, na které by to šlo otestovat. Prosím o urgentní řešení, čeká nám tady 35 000+ stran periodik na export a proarc to už přes rok neumí!

**Comment by luckajirku** [comment]
ve verzi ze 14.10. to vypadá OK

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
