### ISSUE TITLE
Zmizeni STT monografie

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1195]
cituji Martinu Nezbedovou
V pátek 14. 8. se KVO ztratil titul Rachel z ProArcu. Je to STT monografie. Je to stejné jako u mě a u M. Kolářové.
![mlbopnhmffdebiod](https://user-images.githubusercontent.com/37083676/91132836-96165c80-e6ad-11ea-9bae-25a129b152ee.png)

Srp 14, 2020 11:36:57 DOP. org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Jersey Web Application] in context with path [/proarc] threw exception [java.lang.IllegalStateException: Unknown uuid:86666f8f-107d-47f4-9d43-dc56764d0376 in Batch{id=11569, folder=file:/media/vg1-lv1/proarc/work_data/users/vv1876/import/Strahov_2019/RB_II_11/, title=Strahov_2019/RB_II_11/, parentPid=uuid:1d8ad160-834e-4395-85c0-ef5570880dee, create=2020-06-19 08:02:41.34, timestamp=2020-08-14 11:29:14.204, state=INGESTED, userId=38, estimateItemNumber=231, device=device:297fe8ab-47ff-4f4f-955c-037ccf6b0e77, generateIndices=true, profileId=profile.oldprint, log=null}] with root cause
java.lang.IllegalStateException: Unknown uuid:86666f8f-107d-47f4-9d43-dc56764d0376 in Batch{id=11569, folder=file:/media/vg1-lv1/proarc/work_data/users/vv1876/import/Strahov_2019/RB_II_11/, title=Strahov_2019/RB_II_11/, parentPid=uuid:1d8ad160-834e-4395-85c0-ef5570880dee, create=2020-06-19 08:02:41.34, timestamp=2020-08-14 11:29:14.204, state=INGESTED, userId=38, estimateItemNumber=231, device=device:297fe8ab-47ff-4f4f-955c-037ccf6b0e77, generateIndices=true, profileId=profile.oldprint, log=null}
	at cz.cas.lib.proarc.common.imports.ImportBatchManager.findLoadedObjects(ImportBatchManager.java:169)
	at cz.cas.lib.proarc.webapp.server.rest.ImportResource.listBatchItems(ImportResource.java:376)

Ve fedoře záznam existuje.
#1
   pid                uuid:86666f8f-107d-47f4-9d43-dc56764d0376
   state              A
   ownerId            vv1876
   cDate              2020-08-14T09:26:48.519Z
   mDate              2020-08-14T09:26:48.519Z
   title              []
   creator            []
   subject            []
   description        []
   publisher          []
   contributor        []
   date               []
   type               []
   format             []
   identifier         []
   source             []
   language           []
   relation           []
   coverage           []
   rights             []

Stejně tak 231 položek co jsem našel v RELS. 

Petr Kotýnek

**Comment by PetrKotynek** [comment]
Reindex patrně pomohl,
, laicky viděno, prosím o otestování.  
1 M záznamů trvalo 6 1/2 hodiny.

Adding object #1780257: uuid:9e1c8c90-0979-437a-8ca6-c966c0acada9
Adding object #1780258: uuid:cd692bf3-00a6-4527-a1eb-d6f4e18bc270
SUCCESS: 1780258 objects rebuilt.
Finished.

Petr Kotýnek

**Comment by PetrKotynek** [comment]
Asi bez dalších výskytů. PK
