### ISSUE TITLE
Import zvukových dokumentů ve verzi 3.6.3

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1291]
Zdravím,

v verzi 3.6.3 nám přestal fungovat import zvukových dokumentů:

`/home/proarc/.proarc/users/svetlym/import/test/proarc_import/U1-248239842444-01-01-01.foxml cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:fdcae5bb-0bbb-422f-927f-7e0399f01d93, dsId: RAW_AES, jHove cannot generate AES for /home/proarc/.proarc/users/svetlym/import/test/U1-248239842444-01-01-01.wav at cz.cas.lib.proarc.common.fedora.AesEditor.write(AesEditor.java:153) at cz.cas.lib.proarc.common.imports.audio.WaveImporter.createTechnicalMetadata(WaveImporter.java:464) at cz.cas.lib.proarc.common.imports.audio.WaveImporter.consume(WaveImporter.java:121) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSet(SoundRecordingImport.java:121) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSets(SoundRecordingImport.java:102) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.start(SoundRecordingImport.java:89) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:225) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:196) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)`

Filip Šír říkal na Kramériovské schůzce něco o tom, že novej Proarc umí číst technická metadata z audiosouborů a když tam nejsou, umožní jejich editaci. Předpokládám, že v našich starých wavech technická metadata nejsou, tj. varianta s následnou editací nejspíš nefunguje, jak má?

**Comment by SykoraLukas** [comment]
Mohl bych poprosit o zaslání balíčku, který se snažíte importovat? Dekuji

**Comment by svetlym** [comment]
https://drive.google.com/file/d/1TtsEudyHr7BwAFurjD-FBzD-vtk2B3ZK/view?usp=sharing

Michal

Dne 08.03.2021 12:03, SykoraLukas napsal:

**Comment by SykoraLukas** [comment]
Děkuji, mám staženo. Soubor můžete smazat. Opravu se pokusím dodělat do verze 3.6.4 a nejpozději v pátek ji vydám.

**Comment by svetlym** [comment]
Předem díky. Zrovna tohle ale není akutní - zpracování zvukových 
dokumentů zatím jen testujeme, intenzivně ho rozjedeme, až půjde 
importovat do Kraméria, a tedy budeme mít zpětnou vazbu, jak se 
vytvořené dokumenty zobrazujou.

Michal

Dne 08.03.2021 12:29, SykoraLukas napsal:

**Comment by ZdenkaSera** [comment]
@svetlym Prosím, není tohle vzhledem k verzi 3.6.4 k uzavření?

**Comment by svetlym** [comment]
Prosím ještě o strpení, čekáme stále na vyřešení importů do Kraméria. Pak to důkladně otestujeme.

**Comment by ZdenkaSera** [comment]
@svetlym Děkuji za rychlou reakci - já jen po domluvě na schůzce procházím starší věci a zkouším se ptát, jestli jsme je tu jen nezapomněli :-)
