### ISSUE TITLE
test verze 3.6.4. - Chyba při exportu archive 

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1304]
Při exportu Vícedílné monografie na úrovni vícedílky i na úrovni jednoho dílu to hází tuto chybu:
vícedílka: 
![obrazek](https://user-images.githubusercontent.com/24409660/111464210-c3495b80-8720-11eb-968c-e70c31f6b35e.png)
 monografie: 
![obrazek](https://user-images.githubusercontent.com/24409660/111464350-f55abd80-8720-11eb-911c-8c1bf3e3caec.png)
co to znamená? 
Díky

**Comment by PetrKotynek** [comment]
připojuji logy, Petr

[log.zip](https://github.com/proarc/proarc/files/6156981/log.zip)

17-Mar-2021 12:53:24.073 SEVERE [ajp-nio2-127.0.0.1-9009-exec-110] cz.cas.lib.proarc.webapp.server.rest.ExportResource.newArchive null
	java.lang.IllegalStateException: Archivation failed!
		at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archiveImpl(ArchiveProducer.java:99)
		at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archive(ArchiveProducer.java:72)
		at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newArchive(ExportResource.java:551)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
		at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
		at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
		at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
		at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
		at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
		at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
		at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
		at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:525)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1621)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:7d271cdb-2e0d-4637-9cb5-2de548e18959, dsId: RAW, Unsupported entity null
		at cz.cas.lib.proarc.common.export.archive.PackageBuilder.copyStream(PackageBuilder.java:347)
		at cz.cas.lib.proarc.common.export.archive.PackageBuilder.addStreamAsFile(PackageBuilder.java:306)
		at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processDatastreams(ArchiveObjectProcessor.java:162)
		at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:117)
		at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processChildren(ArchiveObjectProcessor.java:237)
		at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:123)
		at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.process(ArchiveObjectProcessor.java:101)
		at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archiveImpl(ArchiveProducer.java:90)
		... 57 more

**Comment by SykoraLukas** [comment]
Můžu poprosit o informaci k jakému modelu se váže ono chybné UUID a o popis onoho vícesvazku? Co všechno obsahuje za modely a nějak základně aspoň nastínit jejich strukturu? 

NDK export se z tohoto vícesvazku udělat dá?

**Comment by SykoraLukas** [comment]
Už informace nepotřebuji, už jsem chybu našel.

**Comment by SykoraLukas** [comment]
Mám opraveno. Jen upozorňuji, že ve verzi 3.6.4 nejde žádný Archivní export.

**Comment by nezbedova** [comment]
Monografie ve v. 3.6.5

DigitalObjectElement{item=model:ndkmonographvolume, uuid:c52ff84c-b48e-4bd5-a2bb-498f6b3976db, Co rostlina ví: průvodce smyslovým světem rostlin, handler=cz.cas.lib.proarc.common.object.DigitalObjectHandler@2cd17a6d}
cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:fd2c9b72-6e87-41c0-8ae8-6fd6f559b557, dsId: RAW, Unsupported entity null
	at cz.cas.lib.proarc.common.export.archive.PackageBuilder.copyStream(PackageBuilder.java:347)
	at cz.cas.lib.proarc.common.export.archive.PackageBuilder.addStreamAsFile(PackageBuilder.java:306)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processDatastreams(ArchiveObjectProcessor.java:162)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:117)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processChildren(ArchiveObjectProcessor.java:237)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:123)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.process(ArchiveObjectProcessor.java:101)
	at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archiveImpl(ArchiveProducer.java:90)
	at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archive(ArchiveProducer.java:72)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newArchive(ExportResource.java:551)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:525)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1621)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tumovam** [comment]
Ve v3.6.5-Snapshop otestován archive export pro NDK Svazek monografie. Od předchozích balíčků se liší:
1. nově workflow_information.xml (souvisí s RDFlow)
2. ve složce NDK se METS jmenuje main_mets_aba007-něconěco.xml , zatímco v dřívejších archivních exportech to byl "pouze" mets_aba007-něconěco.xml . Mohl by to **main_** opravit, prosím, aby se nám nelišily balíčky z různých verzí?
Děkuji, Markéta

**Comment by SykoraLukas** [comment]
Ahoj, tohle bude problém. Standard pro NDK gramofonove desky ma zadefinovane, ze hlavní mets se ma jmenovat main_mets ..... Monografie a periodika nemaji definovany presny nazev a proto, aby se to ulehcilo a bylo na vse mozne pouzivat jednotné názvy a jednotný importer, tak zmena v NDK gramofonových standardech ovlivnila i NDK Monografii i NDK Periodikum.

**Comment by tumovam** [comment]
Ahoj, aha, já to brala podle vzorového SIP balíčku pro periodika, monografie i vícedílky a tam je pouze "mets". Nebylo by jednodušší, kdyby si F. Šír upravil mets pro zvukové dokumenty? :)

**Comment by SykoraLukas** [comment]
Mě to je jedno, ale bylo by skvělé, kdyby NDK Standardy byly stejné i mezi jednotlivými větvemi. Mít jiné názvy složek a souborů pro Gramofonové desky a jiné pro vše ostatní je fakt bordel. A to není první věc, co se jim takto podařila ....

**Comment by tumovam** [comment]
Máš pravdu, koukám i na další věci... master_copy a mastercopy aj. Achjo, napíšu FŠ, příp. na GitHub pro standardy...

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna @nezbedova Navrhuji tohle uzavřít - můžeme? Názvy se vyřešily jinde a jsou opravené (ok i v 3.7.) Děkuji.

**Comment by SmejkalovaAnna** [comment]
Tak snad asi ano za mne

**Comment by nezbedova** [comment]
@ZdenkaSera Jsem pro zavření.

**Comment by ZdenkaSera** [comment]
Děkuji vespolek, zavírám.
