### ISSUE TITLE
Archivní balíček pro eMonografie

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1309]
Ve verzi 3.6.5-Snapshot je možnost exportovat archive balíček pro NDK eMonografie, balíček obsahuje tyto složky:

AUDIT
FOXML
NDK - ve složce NDK jsou tyto soubory: info, md5 a mets
RAW
RELS_EXT
mets

Všechny soubory obsažené ve složkách mají prefix = audit_, foxml_, raw_, rels-ext_

**Comment by tumovam** [comment]
Prosím v NDK složce opravit main_mets_aba007-xyz na mets_aba007-xyz = smazat **main_**. Děkuji, M.

**Comment by SykoraLukas** [comment]
Opravím.

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by tumovam** [comment]
Ad 2.2 Definice SIP balíčku (zde: https://old.ndk.cz/standardy-digitalizace/DMF_ebornmonografie_2.3.pdf ) 
- ve složce NDK by měl být současný NDK export pro eMonografie = složka original (nyní chybí, PDF je ve složce RAW), soubory info, mets a md5 

Issues zatím nemůžeme uzavřít, protože čekáme na NKP až (zda) vymyslí propojení na eKapitoly.

**Comment by SykoraLukas** [comment]
Nechal bych rozlišeno NDK a Archivní balík. Archivní balík nese všechny metadata, NDK je výčet dle NDK standardu.

Jak by tedy měla správně vypadat struktura Archivního balíku?

**Comment by kerschfilip** [comment]
Dobře. V tom případě by bylo asi fajn, aby ta NDK složka představovala samostatný NDK balíček, jako je to u digitalizovaných monografií - aby se dal prostě vzít a rovnou dát do Krameria. Šlo by teda zrušit tu složku RAW a PDFko/epub mít ve složce NDK/original? + doplnit do těch metsů ta technická metadata

**Comment by kerschfilip** [comment]
otestoval jsem u nás na verzi 3.8, Build: 20220525142635, revize e912645b3

V NDK složce archivního balíčku už je PDF a v metsu technická metadata, struktura ale teď vypadá tak, že PDF/epub je jak v té NDK složce, tak ve složce RAW. Připadá mi zbytečné mít v archivním balíčku 2x ten samý soubor. Nešlo by tu složku RAW prostě úplně zrušit, jak jsem psal výše?

**Comment by ZdenkaSera** [comment]
Protože se neobjevil žádný komentář v souvislosti s přiřazením štítku "k realizaci", odebírám štítek "návrh na rozšíření".

**Comment by kerschfilip** [comment]
ve verzi 3.9 vypadá archivní balíček dobře, díky!

nedaří se mi ho ale naimportovat zpátky do ProArcu, chyba při načítání: 
```
java.lang.IllegalStateException: /media/vg1-lv1/proarc-test/work_data/users/fkdigi/import/archive_5ee5111a-f15e-4e35-8815-c953f7186da7/5ee5111a-f15e-4e35-8815-c953f7186da7/mets.xml
	at cz.cas.lib.proarc.common.export.archive.PackageReader.read(PackageReader.java:117)
	at cz.cas.lib.proarc.common.export.archive.ArchiveImport.consumeArchive(ArchiveImport.java:102)
	at cz.cas.lib.proarc.common.export.archive.ArchiveImport.consume(ArchiveImport.java:95)
	at cz.cas.lib.proarc.common.export.archive.ArchiveImport.load(ArchiveImport.java:68)
	at cz.cas.lib.proarc.common.export.archive.ArchiveImport.start(ArchiveImport.java:61)
	at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:253)
	at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:224)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Invalid file: /media/vg1-lv1/proarc-test/work_data/users/fkdigi/import/archive_5ee5111a-f15e-4e35-8815-c953f7186da7/5ee5111a-f15e-4e35-8815-c953f7186da7/RAW/raw_ndkemonographvolume_0001_5ee5111a-f15e-4e35-8815-c953f7186da7.pdf, FileType{ID: RAW_ndkemonographvolume_0001_5ee5111a-f15e-4e35-8815-c953f7186da7, MIME: application/pdf, FLocat: [FLocat{href: ./RAW/raw_ndkemonographvolume_0001_5ee5111a-f15e-4e35-8815-c953f7186da7.pdf, LOCTYPE: URL}]}
	at cz.cas.lib.proarc.common.export.archive.PackageReader.toFile(PackageReader.java:625)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.createDatastream(PackageReader.java:497)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.createDatastreams(PackageReader.java:399)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.processObject(PackageReader.java:335)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.readImpl(PackageReader.java:136)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.read(PackageReader.java:115)
	... 13 more

nehledá se to PDF v té původní složce RAW?
```

**Comment by SykoraLukas** [comment]
Ano je to tak. Byla tam chyba, že se sice RAW složka smazala, ale mets archivního balíčku na ni stále odkazoval.

**Comment by kerschfilip** [comment]
ve verzi 3.9.1 funguje export i import archivního balíčku e-monografie. Díky!
