### ISSUE TITLE
Jak generovat NDK balíček na zkoušku bez URN:NBN

### ISSUE THREAD

**Issue by eliasskrd** [proarc/proarc#1383]
Scénář: potřebuji vygenerovat NDK či archivační balíček, a poslat ke schválení do NDK (či jinak použít). V současné verzi je možno export provést patrně jen se zadaným URN:NBN. To pak však nelze odstranit.
Buďto povolit generaci exportu bez zadaného URN:NBN, nebo povolit zadání testovacího (např. 'pokus123'), a jeho následné odstranění / nahrazení platným vygenerovaným URN:NBN?

děkujeme!

**Comment by luckajirku** [comment]
A variantu, že byste si domluvili v NK v resolveru pro vaši instituci testovací účet jste nezkoušel? Ozkoušeli byste tak celý proces jak má být, včetně komunikace s resolverem. Ohýbat ProArc mi v tomhle nepřijde rozumné, je naprosto v pořádku, že systém nepovolí export NDK balíčku bez URN:NBN.

**Comment by eliasskrd** [comment]
Testovací účet máme, ale tohle neřeší. Jedná se nikoliv o ozkoušení provozu, ale o provoz.
možnosti:
- chci poslat hotový balíček do NDK, a požádat je o zpětnou vazbu. Následně poupravit metadata, přidělit urn:nbn, a vyexportovat. Podle mě smysluplný a běžný scénář, alespoň na takovou to potřebu narážím neustále.
- momentálně nechci přidělovat urn:nbn, chceme udělat až posléze, ale potřebuji si vytvořit archivní balíček, uvolnit ProArc, později naimportovat, dodělat, přidělit urn:nbn

V současné situaci je použití pro nás velmi nepraktické, až funkčnost blokující. Nevím, jeslti na to koukáte z praktického hlediska, ale začarovaný kruh: abych vyrobil balíček, musím přidělit urn:nbn, ale když je vyrobený balíček v něčem nevyhovující, již jej nemohu měnit (a patrně musím tedy záznam v ProArc vyrábět znova?) dost fatální nedostatek. K tomu je to omezení volby - proč bych si nemohl nejprve na zkoušku vyexportovat balíčky jak chci, nechat je zkontrolovat, validovat či podobně, a pak přidělit urn:nbn až opravdu validnímu  a platnému? Podle mě by to bylo logické.

Jeslti je to problém, kdo prosím rozhoduje o nastavení workflow? Mám kontaktovat Národní digit. knih. a zkusit to dohodnout s nima?

díky!

**Comment by luckajirku** [comment]
Právě z praktického hlediska se na to dívám a nerozumím té metodě pokus-omyl. Jak moc velké změny a jak často musíte dělat? My se snažíme jít spíš cestou prevence - tedy mít co nejlepší katalogizační záznamy, dělat důslednou kontrolu během zpracování atd. Těch případů, kdy je třeba po exportu z ProArcu zneplatnit URN:NBN a přidělit nové je pak minimum.

**Comment by SykoraLukas** [comment]
Souhlasím s @luckajirku. Testovací účet v testovacím resolveru toto řeší.

NDK balíček bez URN:NBN dělat nelze - poté by to nebyl NDK balíček (viz specifikace NDK balíčků na stránkách NDK).

Ale toto by měl být postup práce ve Vašem případě:
- Vytvořím objekt a k němu stránky (vše připraveno na export)
- Objektu dám URN:NBN a k tomu jsou 2 možnosti.
a) přidělím URN:NBN z testovacího resolveru
b) ve formuláře objektu vytvořím URN:NBN ručně.
- Balíček vyexportuji a pošlu do NDK ke kontrole
- Dělám případné opravy
- Pokud mám schváleno, že je balíček validní tak ve formuláři objektu přidám danému URN:NBN status Neplatný
- Přidělím URN:NBN z produkčního účtu resolveru.

**Comment by SykoraLukas** [comment]
@nezbedova @ZdenkaSera @SmejkalovaAnna můžete prosím tuto možnosti postupu doplnit do uživatelské dokumentace k sekci URN:NBN? Děkuji

**Comment by eliasskrd** [comment]
Děkuji za informaci.
Přecejen někdy potřebujeme vyexportovat předběžně, například za účelem konzultace nebo zkusit validátor.
Jestliže zneplatnění testovacího urn:nbn a následné přiřazení produkčního je korektní, patrně vyřešeno.

děkujeme moc!

**Comment by SmejkalovaAnna** [comment]
Udělám, přidám ještě dnes.

**Comment by eliasskrd** [comment]
Dobrý den,
nejsem si jist, zda vámi uvedený návod funguje - po přidělění a zneplatnění testovacího urn:nbn asi nejde přidělit z produkčního resolveru?
Na verzi 3.7.1 jsem přidělil ručně testovací urn:nbn, vyexportoval, nastavil 
dané urn:nbn jako Neplatné, klikl na Titul a na tlačítko '+ URN:NBN', výsledkem chyba 1. Když zkusím znova, vyskočí chyba 2 - patrně na resolveru se záznam při prvním pokusu vytvořil, ale nezapsal do metadat titulu.
děkujeme!

chyba 1.
java.lang.IllegalStateException: uuid:e811f522-7b4e-4928-a156-f7e29ebfd78f: Cannot write URN:NBN urn:nbn:cz:aba009-000a2g
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:783)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.processNdkMonographVolumeOrSupplement(UrnNbnVisitor.java:617)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkMonographVolume(UrnNbnVisitor.java:201)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkMonographVolume(UrnNbnVisitor.java:79)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:51)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:118)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:79)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnService.register(UrnNbnService.java:72)
	at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.registerUrnNbn(DigitalObjectResource.java:1923)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: cz.cas.lib.proarc.common.fedora.DigitalObjectValidationException: PID: uuid:e811f522-7b4e-4928-a156-f7e29ebfd78f, dsId: BIBLIO_MODS, MODS validation
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkBeforeWrite(NdkMetadataHandler.java:624)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetadataHandler.java:711)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadata(NdkMetadataHandler.java:142)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:778)
	... 62 more

chyba 2:
INVALID_REGISTRAR_SCOPE_IDENTIFIER: for registrar 'aba009' there already exists registrar-scope identifier with either type 'uuid' for digital document 3127085, or type 'uuid' and value 'e811f522-7b4e-4928-a156-f7e29ebfd78f' for some other digital document

**Comment by ZdenkaSera** [comment]
@eliasskrd Dovolím si komentář z naší praxe - stalo se nám totéž, a to v situaci, kdy byla metadata titulu uložena s chybou. Postupovali jsme pak takto:
1. našli a opravili jsme chybu v metadatech
2. podle uuid jsme v resolveru ověřili, jaké urn:nbn bylo přiděleno
3. toto urn:nbn jsme ručně zapsali do metadat a uložili
4. zkusili jsme je znovu přidělit a resolver vrátil v dialogu potvrzení, že toto uuid už má urn:nbn

**Comment by eliasskrd** [comment]
děkuji moc za radu!
Už jsem mezitím také zjistil, že přidělit platné URN:NBN z resolveru lze ručně, což je řešení. Stejně se patrně jedná o chybu, mělo by být možné přidělit automaticky..

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
