### ISSUE TITLE
v 3.9/akubra logy z prvniho "běhu"

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1515]
Zasílám logy a konfigurace ze zkušebního jetí, v pruběhu jsem zkoušel na "proarc" importovat nějaký balíček a reindexovat 
vše. Ale chyby budou hrubšího zrna.  Možná tam bude něco vidět. PK
 
[9.zip](https://github.com/proarc/proarc/files/10193378/9.zip)

**Comment by PetrKotynek** [comment]
Zdravím,
po několika reinstalacích jsem zakotvil u solru 8.11.0 s nejmenším počtem varování. 
Dokonce jsem i něco protlačil z PA do solru, viz níže.
Trvá  problém se čtením low level "akubra" struktur zděděných po Fedoře. 
Zkoušel jsem nastavit -Dhazelcast.diagnostics.enabled=true. ale příliš informací jsem nezískal.   

![bez_objektu](https://user-images.githubusercontent.com/37083676/210338415-d1a1b0e6-7f76-48ce-ad09-26a292cfcbe8.png)
![search_pod_kontrola](https://user-images.githubusercontent.com/37083676/210338452-4abb12f8-cd03-487b-a133-42255cd66680.png)

![warn_8 11 0](https://user-images.githubusercontent.com/37083676/210338582-fb8e7a01-c168-4563-9bb1-b2c204f8609b.png)


PK

03-Jan-2023 09:16:31.003 INFO [akubrasync.internal-2] com.hazelcast.client.connection.ClientConnectionManager.null akubrasync [dev] [3.11.2] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:54259->/127.0.0.1:5701}, remoteEndpoint=[172.16.62.28]:5701, lastReadTime=2023-01-03 09:16:31.000, lastWriteTime=2023-01-03 09:16:30.977, closedTime=never, connected server version=3.11.2} as owner with principal ClientPrincipal{uuid='a862f410-09d2-4dc3-b6f6-d00e1f25ef95', ownerUuid='077af7f8-a95e-4cb4-a6c9-d14b7471d21e'}
03-Jan-2023 09:16:31.003 INFO [akubrasync.internal-2] com.hazelcast.client.connection.ClientConnectionManager.null akubrasync [dev] [3.11.2] Authenticated with server [172.16.62.28]:5701, server version:3.11.2 Local address: /127.0.0.1:54259
03-Jan-2023 09:16:31.008 INFO [hz.akubrasync.client.thread-1] com.hazelcast.internal.partition.impl.PartitionStateManager.null [172.16.62.28]:5701 [dev] [3.11.2] Initializing cluster partition table arrangement...
03-Jan-2023 09:16:31.032 INFO [akubrasync.event-7] com.hazelcast.client.spi.impl.ClientMembershipListener.null akubrasync [dev] [3.11.2]

Members [1] {
        Member [172.16.62.28]:5701 - 077af7f8-a95e-4cb4-a6c9-d14b7471d21e
}

03-Jan-2023 09:16:31.034 INFO [akubrasync.cluster-] com.hazelcast.core.LifecycleService.null akubrasync [dev] [3.11.2] HazelcastClient 3.11.2 (20190216 - e302506) is CLIENT_CONNECTED
03-Jan-2023 09:16:31.034 INFO [ajp-nio-0.0.0.0-9009-exec-4] com.hazelcast.internal.diagnostics.Diagnostics.null akubrasync [dev] [3.11.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
03-Jan-2023 09:16:31.226 INFO [ajp-nio-0.0.0.0-9009-exec-4] org.ehcache.core.EhcacheManager.createCache Cache 'DigitalObjectCache' created in EhcacheManager.



2023-01-02 09:56:01.827 INFO  (qtp708533063-14) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=86
2023-01-02 09:56:01.899 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 09:56:07.131 INFO  (qtp708533063-22) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:56:07.144 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0


2023-01-02 09:57:58.456 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:57:58.462 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:59:12.609 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=4
2023-01-02 09:59:12.622 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 09:59:19.046 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:59:19.057 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:59:36.870 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 09:59:36.876 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:07:31.926 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=3
2023-01-02 10:07:31.933 INFO  (qtp708533063-14) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:08:23.503 INFO  (qtp708533063-23) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:08:23.510 INFO  (qtp708533063-23) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 10:08:31.079 INFO  (qtp708533063-14) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 10:08:31.088 INFO  (qtp708533063-23) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:25:49.018 INFO  (qtp708533063-19) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:25:49.025 INFO  (qtp708533063-14) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:29:56.338 INFO  (qtp708533063-22) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:29:56.352 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:30:03.817 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 10:30:03.825 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:30:55.873 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 10:30:55.881 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:device"+OR+"proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:31:53.925 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:31:53.933 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-02 10:32:06.548 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:32:06.563 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-02 10:33:53.463 INFO  (qtp708533063-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:33:53.473 INFO  (qtp708533063-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=7
2023-01-02 10:33:53.486 INFO  (qtp708533063-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=1
2023-01-02 10:33:55.930 INFO  (qtp708533063-23) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:33:55.935 INFO  (qtp708533063-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=5
2023-01-02 10:33:55.939 INFO  (qtp708533063-23) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/logging params={wt=json&_=1672651904860&since=0} status=0 QTime=1
2023-01-02 10:33:59.954 INFO  (qtp708533063-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/logging params={wt=json&_=1672651904860} status=0 QTime=1
2023-01-02 10:33:59.955 INFO  (qtp708533063-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=3
2023-01-02 10:33:59.958 INFO  (qtp708533063-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:03.158 INFO  (qtp708533063-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:03.168 INFO  (qtp708533063-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=8
2023-01-02 10:34:03.179 INFO  (qtp708533063-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=1
2023-01-02 10:34:05.430 INFO  (qtp708533063-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:05.433 INFO  (qtp708533063-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=11
2023-01-02 10:34:05.433 INFO  (qtp708533063-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=10
2023-01-02 10:34:05.473 INFO  (qtp708533063-20) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:05.474 INFO  (qtp708533063-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:05.481 INFO  (qtp708533063-20) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=6
2023-01-02 10:34:10.130 INFO  (qtp708533063-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:34:10.134 INFO  (qtp708533063-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/properties params={wt=json&_=1672652324891} status=0 QTime=0
2023-01-02 10:34:10.137 INFO  (qtp708533063-23) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=4
2023-01-02 10:35:11.663 INFO  (qtp708533063-22) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1672651469301} status=0 QTime=2
2023-01-02 10:35:11.664 INFO  (qtp708533063-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:35:11.696 INFO  (qtp708533063-22) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/threads params={wt=json&_=1672652274843} status=0 QTime=30
2023-01-02 10:35:18.389 INFO  (qtp708533063-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1672651469301} status=0 QTime=0
2023-01-02 10:35:18.399 INFO  (qtp708533063-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system

**Comment by PetrKotynek** [comment]
Prolinkoval jsem v hlavním adresáři PA

ln -s fedora .proarc

abych se více přiblížil stylu akubra.cfg.template:
#Akubra store
objectStore.path=${sys:user.home}/.proarc/data/objectStore
objectStore.pattern=##/##
datastreamStore.path=${sys:user.home}/.proarc/data/datastreamStore
datastreamStore.pattern=##/##

Podeziral jsem PA z ignorování akubra.cfg.

04-Jan-2023 09:01:48.292 SEVERE [ajp-nio-0.0.0.0-9009-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlt [Jersey Web Application] in context with path [/proarc] threw exception [org.fcrepo.common.FaultException: System error opening output strea] with root cause
        java.io.IOException: Unable to create parent directory: /home/tomcat.proarc/data/objectStore/7c
                at org.akubraproject.fs.FSBlob.makeParentDirs(FSBlob.java:237)


Failed to create digital object.

pid : [PID: uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61, Object with PID uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61 already exists!]


ručně jsem vytvořil uuid:6b4ddaba-befb-4b3e-ad85-60684a930b69

A něco málo to dělá viz dále , třeba to evidentně hrábne do akubra repo do části objectStore .
PK


tomcat@bigfedo:~/.proarc/data/objectStore/06$ ls -la
total 60
drwxr-x---   2 tomcat tomcat  4096 Jan  4 09:25 .
drwxr-x--- 258 tomcat tomcat  4096 Jan 21  2021 ..
-rw-r-----   1 tomcat tomcat  4528 Jan 19  2021 info%3Afedora%2Fdemo%3ASmileyStuff
-rw-r-----   1 tomcat tomcat 13769 Nov 15 14:13 info%3Afedora%2Fuuid%3A40d1b321-f34b-4b8a-9645-0563490ba5e9
-rw-r-----   1 tomcat tomcat  2623 Jan  4 09:25 info%3Afedora%2Fuuid%3A6b4ddaba-befb-4b3e-ad85-60684a930b69
-rw-r-----   1 tomcat tomcat 23208 Nov 15 14:13 info%3Afedora%2Fuuid%3Acbe19a1f-096b-4680-9312-99b69abe2e0c



2023-01-04 08:13:20.624 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:13:20.629 INFO  (qtp708533063-18) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0



root@bigfedo:/var/solr/logs# cat solr.log |grep 6b4ddaba-befb-4b3e-ad85-60684a930b6
2023-01-04 08:13:20.624 INFO  (qtp708533063-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:13:20.629 INFO  (qtp708533063-18) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:25:39.369 INFO  (qtp708533063-21) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b69")&start=0&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:26:15.298 INFO  (qtp708533063-21) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b69")&start=0&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:27:01.119 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b69")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-04 08:27:01.125 INFO  (qtp708533063-21) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b69")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:32:25.333 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:32:25.341 INFO  (qtp708533063-19) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1
2023-01-04 08:32:29.592 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-04 08:32:29.599 INFO  (qtp708533063-19) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("null")+AND+pid:("uuid:6b4ddaba-befb-4b3e-ad85-60684a930b61")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=0

**Comment by PetrKotynek** [comment]
Srovnávám běh PA/FEDORA a PA/AKUBRA pomocí Wiresharku. FC repository prázné po ztrátě konzistence a reinitu. 
Zatímco PA/FEDORA FEDORA načte příslušné údaje přes HTML z FC PA/AKUBRA se ničeho takového nedočká.

2023-01-06 09:46:58.698 INFO  (qtp708533063-17) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=model:("proarc:audiodevice")&start=0&rows=1000&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-06 10:53:34.894 INFO  (qtp708533063-21) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=2147483647&wt=javabin&version=2} hits=0 status=0 QTime=0
2023-01-06 10:53:34.926 INFO  (qtp708533063-20) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/select params={q=state:"Active"+AND+model:("model:ndkperiodical")&start=0&rows=100&wt=javabin&version=2} hits=0 status=0 QTime=1

Jako by chyběl počáteční "init"
to co se kdysi dělal pomocí:
cd proarc-models/
fedora-ingest.sh d ./ 'info:fedora/fedora-system:FOXML-1.1' 127.0.0.1:8090 fedoraAdmin fedoraAdmin http ""
???

PK

**Comment by PetrKotynek** [comment]
1. záměna 127.0.0.1 localhost bez vlivu na funkčnost. ipv6 

2. PA/AKUBRA vykazuje nějaké chyby na AJP portu, ale pouze při restartu Tomcatu. V ustáleném režimu síť běží v
 bez nějakých zjevných vad.


 nmap -p 8983 localhost
Starting Nmap 5.21 ( http://nmap.org ) at 2014-07-17 10:21 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000079s latency).
PORT     STATE SERVICE
8983/tcp open  unknown

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9005          0.0.0.0:*               LISTEN      1157/java
tcp        0      0 127.0.0.1:7983          0.0.0.0:*               LISTEN      1438/java
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      4964/apache2
tcp        0      0 0.0.0.0:9009            0.0.0.0:*               LISTEN      1157/java
tcp        0      0 127.0.0.1:3350          0.0.0.0:*               LISTEN      1156/xrdp-sesman
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1124/sshd: /usr/sbi
tcp        0      0 0.0.0.0:8983            0.0.0.0:*               LISTEN      1438/java
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      1219/postgres
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      1157/java
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      4964/apache2
tcp        0      0 0.0.0.0:3389            0.0.0.0:*               LISTEN      1183/xrdp
tcp        0      0 0.0.0.0:5701            0.0.0.0:*               LISTEN      1157/java

![capt1](https://user-images.githubusercontent.com/37083676/211004017-12f52bb0-be55-41ff-a2e2-019b37281c9c.png)


PK

**Comment by PetrKotynek** [comment]
Kontrola database fedora3 PK

[fedora3_dump.txt](https://github.com/proarc/proarc/files/10434954/fedora3_dump.txt)

**Comment by PetrKotynek** [comment]
Zkoušel jsem možný vliv Tomcat/Java na AKUBRA verzi
v souvislosti s release poznámkou v 3.9.1 a wiki Rozběhnutí Proarc 3.9.1 a novější pod Tomcat 7

Bez chyb nabíhají kombinace Java 8 a to jak poslední 2 Oracle tak OpenJDK. 
openjdk version "1.8.0_352-352" java version "1.8.0_351"
spolu s
apache-tomcat-8.5.84 apache-tomcat-8.5.72 aktuální apache-tomcat-9

Apache Tomcat Version 11.0.0-M1
naopak  nelze spustit pro 

Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED
a následné 
SEVERE: Error configuring application listener of class [cz.cas.lib.proarc.webapp.server.EditorServletConfiguration]
java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
nebo  ( Java 11 )
tomcat@bigfedo:~/apache-tomcat/logs$ cat catalina.out
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/catalina/startup/Bootstrap has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by PetrKotynek** [comment]
Kombinace 
java version "1.8.0_351" a posledního  Apache Tomcat Version 10.0.27 vede k

SEVERE: Error configuring application listener of class [cz.cas.lib.proarc.webapp.server.EditorServletConfiguration]
java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
	at java.lang.ClassLoader.defineClass1(Native Method)

[log.zip](https://github.com/proarc/proarc/files/10444013/log.zip)

**Comment by PetrKotynek** [comment]
4.0.1
