### ISSUE TITLE
Java heap space při exportu souboru gramodesek

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1526]
Při exportu souboru většího počtu gramodesek (Kramérius export) Proarc hází následující chybu:

```
cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: null, Java
heap space
    at
cz.cas.lib.proarc.common.export.Kramerius4Export.export(Kramerius4Export.java:271)
    at
cz.cas.lib.proarc.webapp.server.rest.ExportResource.kramerius4(ExportResource.java:209)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at
org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at
org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
    at
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at
org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at
org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at
org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at
org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at
org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
    at
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
    at
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
    at
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at
cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:77)
    at
cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at
cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at
org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at
org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:750)
```

Dělá to i čerstvě po restartu celýho linuxu.

**Comment by SykoraLukas** [comment]
Jak je nastavený context? Jaké jsou parametry povolené pro JAVU?

**Comment by svetlym** [comment]
Nejsem si popravdě jistej. Při nedávnym řešení problému s refreshováním dat v klientu jste nám předělali startup Proarcu na service, takže se už nejspíš nevolá můj původní startup skript. Podle všeho se teď žádný parametry nepředávaj:

/etc/systemd/system/proarc.service

```
[Unit]
Description=The ProArc Tomcat
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
WorkingDirectory=/home/proarc/fedora/tomcat

ExecStart=/bin/bash /home/proarc/fedora/tomcat/bin/catalina.sh start
ExecStop=/bin/bash /home/proarc/fedora/tomcat/bin/catalina.sh stop

User=proarc
Group=proarc
RestartSec=20
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by SykoraLukas** [comment]
@pkudela mohl bys na to prosím kouknout a případně navýšit velikost heapu JAVY?

**Comment by pkudela** [comment]
Dobry den @svetlym udelali jsme potrebne konfigurace v service proarcu, psal jsem Katce, at to otestuje.

**Comment by katerinasirova** [comment]
Otestováno, zatím všechny minule neexportované desky vyexportovány a vyzkoušeny i 3 velké soubory (10 desek, 5 desek a 3 desky). Vše prošlo. @svetlym zkusí naimportovat do Krameria. Dáme vědět, jak to dopadlo. Díky

**Comment by svetlym** [comment]
Jelikož při defaultních parametrech pro spouštění Javy nefungujou některý exporty, chtělo by zmínit v dokumentaci, že je potřeba je změnit a uvést doporučený hodnoty.

Za nás je jinak problém vyřešen.
