### ISSUE TITLE
Chyba při importu zvukového dokumentu do Kraméria

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1527]
Testujeme funkčnost K4 exportu zvukových dokumentů. První pokus o import do Kraméria zafungoval, další spadnul s následující chybou:

```
Jan 17, 2023 5:15:21 PM org.kramerius.Import ingest
SEVERE: Ingest SOAP fault:javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
Jan 17, 2023 5:15:21 PM org.kramerius.Import ingest
SEVERE: Ingestion error 
java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
	at org.kramerius.Import.ingest(Import.java:400)
	at org.kramerius.Import.ingest(Import.java:423)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:308)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:243)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:243)
	at org.kramerius.Import.ingest(Import.java:131)
	at org.kramerius.Import.main(Import.java:98)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy49.ingest(Unknown Source)
	at org.kramerius.Import.ingest(Import.java:357)
	... 12 more

Jan 17, 2023 5:15:21 PM org.kramerius.Import visitAllDirsAndFiles
SEVERE: Error when ingesting PID: uuid:f3b2bc76-e302-4ef2-b0b3-0f81ad4a66f7, java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
Jan 17, 2023 5:15:21 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:313)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:243)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:243)
	at org.kramerius.Import.ingest(Import.java:131)
	at org.kramerius.Import.main(Import.java:98)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	... 5 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
	at org.kramerius.Import.ingest(Import.java:426)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:308)
	... 10 more
Caused by: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: Text size limit (134217728) exceeded
 at [row,col {unknown-source}]: [1,134221673] 
	at org.kramerius.Import.ingest(Import.java:400)
	at org.kramerius.Import.ingest(Import.java:423)
	... 11 more
Caused by: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error
```

**Comment by vlahoda** [comment]
Importovany FOXML dokument je prilis velky (zrejme kvuli obsazenym zvukovym stopam v BASE64 kodovani) a Fedora ho nemuze nacist. @SykoraLukas :  bude potreba zmenit format zvukovych datastreamu na externe referencovane. A neo pockat s prechodem na K7.

**Comment by SykoraLukas** [comment]
Nutné řešit na straně Krameria - bude řešeno v K7.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
