### ISSUE TITLE
v3.9/akubra 391 chyba v new FedoraTransaction(remoteStorage)

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1530]
odejde na null
na tento   FedoraTransaction ftx = null;
   new FedoraTransaction(remoteStorage);
   ma byt asi ftx = new FedoraTransaction(remoteStorage);

PK

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Group{id=null, name=group:admin, title=Administrátoři, remoteName=null, remoteType=null, created=null, timestamp=null}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at cz.cas.lib.proarc.webapp.server.ProarcInitializer.isReady(ProarcInitializer.java:84)
        at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:885)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1688)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Group{id=null, name=group:admin, title=Administrátoři, remoteName=null, remoteType=null, created=null, timestamp=null}
        at cz.cas.lib.proarc.common.user.UserManagerSql.addGroup(UserManagerSql.java:277)
        at cz.cas.lib.proarc.common.user.UserUtil.initDefaultAdmin(UserUtil.java:181)
        at cz.cas.lib.proarc.webapp.server.ProarcInitializer.asyncInitialization(ProarcInitializer.java:145)
        at cz.cas.lib.proarc.webapp.server.ProarcInitializer.access$000(ProarcInitializer.java:63)
        at cz.cas.lib.proarc.webapp.server.ProarcInitializer$1.call(ProarcInitializer.java:115)
        at cz.cas.lib.proarc.webapp.server.ProarcInitializer$1.call(ProarcInitializer.java:111)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.lang.NullPointerException: tx
        at cz.cas.lib.proarc.common.fedora.FedoraDao.setTransaction(FedoraDao.java:33)
        at cz.cas.lib.proarc.common.user.UserManagerSql.addGroup(UserManagerSql.java:265)
        ... 9 more

@Override
    public Group addGroup(Group group, List<Permission> permissions, String owner, String log) {
        if (!UserUtil.isValidGroupPid(group.getName())) {
            throw new IllegalArgumentException("groupName: " + group.getName());
        }
        Transaction tx = daos.createTransaction();
        GroupDao groupDao = daos.createUserGroup();
        groupDao.setTransaction(tx);
        FedoraTransaction ftx = null;
        try {
            // fedora
            if (Storage.FEDORA.equals(appConfig.getTypeOfStorage())) {
                new FedoraTransaction(remoteStorage);
                FedoraGroupDao fedoraGroups = new FedoraGroupDao();
                fedoraGroups.setTransaction(ftx);
                fedoraGroups.addGroup(group, owner, log);
            }
            groupDao.update(group);
            if (!permissions.isEmpty()) {
                permissionStorage.set(((SqlTransaction) tx).getConnection(), group.getId(),
                        permissions.toArray(new Permission[permissions.size()]));
            }
            commit(tx, ftx);
            return group;
        } catch (Throwable ex) {
            rollback(tx, ftx);
            throw new IllegalStateException(String.valueOf(group), ex);
        } finally {
            close(tx, ftx);
        }

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosíme o reakci s nejvyšší prioritou. Díky.

**Comment by PetrKotynek** [comment]
Už jsem to buildnul a naběhlo to v tomcatu. PK



[INFO] ProArc Common Library .............................. SUCCESS [  8.583 s]
[INFO] ProArc Authentication .............................. SUCCESS [  0.279 s]
[INFO] ProArc Web Application ............................. SUCCESS [03:35 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:05 min
[INFO] Finished at: 2023-02-14T14:14:38+01:00
[INFO] ------------------------------------------------------------------------

+ autorizace tokenem k
<repository>
         <id>kramerius</id>
          <url>https://maven.pkg.github.com/ceskaexpedice/kramerius</url>

proarc-commons  pom.xml - fast-md5 2.5 - nejde nejde a nejde zlomit
+

<dependency>
    <groupId>com.joyent.util</groupId>
    <artifactId>fast-md5</artifactId>
    <version>2.7.1</version>
</dependency>



 mvn -B com.isomorphic:isc-maven-plugin:1.1.1:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=6.0p -DbuildDate=2022-05-28

 mvn clean install -U -P proarc.production  -DskipTests=true

**Comment by SykoraLukas** [comment]
Vzhledem k tomnu, že vznikají závislosti mezi ProArcem a Krameriem, je potřeba aby uživatel měl ve své .m2 složce nastavený Personal Access token na github. Pokud toto nemáte, nedokážete stáhnout Kramerius package a tím se nepodaří vytvořit build.
Zvládnete si toto nastavit sám? Případně pošlu mailem ukázky a návod co a jak udělat.

**Comment by PetrKotynek** [comment]
Ano, bez toho to vůbec nešlo. Díky. Ale je tam další chyba v dependency,
jak již jsem byl psal, s fast-md5 2.7.1 jsem to *sestavil* ale
je to špatně běhově. Vadí právě v low-level akubra. Koukal jsem do
Krameria. Tam je použit ten samý fast-md5 2.5 ale nezastavuje se Mavenem.
PK

     </repository> -->
         <repository>
         <id>kramerius</id>
          <url>https://maven.pkg.github.com/ceskaexpedice/kramerius</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
<server>
      <id>kramerius</id>
      <username>PetrKotynek</username>
      <password>Token</password>
    </server>

**Comment by SykoraLukas** [comment]
Opraveno ve vezi 4.0.1
