### ISSUE TITLE
400-dev problem behu java.sql.SQLException: Cannot get a connection pool error

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1546]
jenstejn test 400-dev prestal chodit nepomaha restart tomcatu, po chvili se nejde přihlasit.

zkoušel jsem navrat ke 3.9 ale tam jsou problemy se versi db

MD mi informoval, že je tam 512 konexí. Ještě se podívám do context.xml.

Petr Kotýnek

SEVERE: ImportDispatcher-pool-4-thread-1
java.lang.IllegalStateException: java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
	at cz.cas.lib.proarc.common.dao.empiredb.EmpireDaoFactory.createTransaction(EmpireDaoFactory.java:60)
	at cz.cas.lib.proarc.common.dao.empiredb.EmpireDaoFactory.createTransaction(EmpireDaoFactory.java:29)
	at cz.cas.lib.proarc.common.imports.ImportBatchManager.update(ImportBatchManager.java:311)
	at cz.cas.lib.proarc.common.imports.ImportProcess.logBatchFailure(ImportProcess.java:225)
	at cz.cas.lib.proarc.common.imports.ImportProcess.logBatchFailure(ImportProcess.java:218)
	at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:269)
	at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:230)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
	at org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:142)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at cz.cas.lib.proarc.common.dao.empiredb.EmpireConfiguration.getConnection(EmpireConfiguration.java:98)
	at cz.cas.lib.proarc.common.dao.empiredb.EmpireDaoFactory.createTransaction(EmpireDaoFactory.java:56)
	... 13 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:443)
	at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:353)
	at org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	... 16 more

[10.zip](https://github.com/proarc/proarc/files/10942544/10.zip)

db vypada v provozu
proarc=> \l
                                            Seznam databází
        Jméno         |    Vlastník     | Kódování  |  Collation  |    CType    |   Přístupová práva
----------------------+-----------------+-----------+-------------+-------------+-----------------------
 fedora-3.8.1         | fedoraAdmin     | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 fedora-3.8.1-test    | fedoraAdminTest | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 postgres             | postgres        | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 proarc               | proarcAdmin     | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 proarc-test          | proarcAdminTest | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 riTriples-3.8.1      | fedoraAdmin     | SQL_ASCII | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 riTriples-3.8.1-test | fedoraAdminTest | SQL_ASCII | cs_CZ.UTF-8 | cs_CZ.UTF-8 |
 template0            | postgres        | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 | =c/postgres          +
                      |                 |           |             |             | postgres=CTc/postgres
 template1            | postgres        | UTF8      | cs_CZ.UTF-8 | cs_CZ.UTF-8 | postgres=CTc/postgres+
                      |                 |           |             |             | =c/postgres

**Comment by PetrKotynek** [comment]
pritlacil jsem na maxTotal="150" a otocil tomcat PK

**Comment by SykoraLukas** [comment]
Zapomněl jsem zavřít transakci do BD, při zjišťování stavu procesu LOADING. Mám opraveno, do pondělí vydám nový build, který toto bude opravovat. 

Pokud je vypnutý tomcat, kolik procesů aktivních procesů hlásí BD? Mělo by to být v řádu jednotek.

**Comment by mduda100871** [comment]
Předpokládám že BD je DB, tedy databáze.

Podle toho chování jsem předpokládal/tipnul, že aplikace nekorektně uzavírá spojení s DB, takže to po chvíli vyčerpalo connection pool. Tímto se to tedy potvrdilo.

PostgreSQL má standardně povoleno 150 spojení, což běžně bohatě stačí pokud se aplikace chovají korektně. Naše instance má nastaveno 512 povolených spojení, protože tam zároveň běží i testovací instance.

Pokud je deaktivovaný tomcat, tak DB nemá prakticky žádné aktivní procesy - jen své vlastní, podpůrné.
MD

**Comment by SykoraLukas** [comment]
Oprava vydána [build 4.0.1](https://github.com/proarc/proarc/releases/tag/v4.0.1)
