### ISSUE TITLE
4.0.2 akubra upgrade zamenou war souboru

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1563]
Generuje následující chybu.  Dokonce nezabírá ani ... restart tomcat, až po pomalém ... stop tomcat ... start tomcat si to nechá
říci. Někdy. PK

14-Apr-2023 11:09:20.973 INFO [hz.akubrasync.cached.thread-3] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.internal.cluster.MemberInfo]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.internal.cluster.MemberInfo]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1440)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1428)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1267)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1228)
                at com.hazelcast.internal.cluster.impl.MembersView.createNew(MembersView.java:86)
                at com.hazelcast.internal.cluster.impl.MemberMap.toMembersView(MemberMap.java:225)
                at com.hazelcast.internal.cluster.impl.MembershipManager.sendMemberListToOthers(MembershipManager.java:239)
                at com.hazelcast.internal.cluster.impl.MembershipManager.publishMemberList(MembershipManager.java:218)
                at com.hazelcast.internal.cluster.impl.MembershipManager.access$000(MembershipManager.java:78)
                at com.hazelcast.internal.cluster.impl.MembershipManager$1.run(MembershipManager.java:119)
                at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
                at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:750)
                at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
                at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím tě, je tahle chyba něco, co bude vyžadovat vývoj? Děkuji.

**Comment by SykoraLukas** [comment]
Vypadá to, že se jen špatně spustilo warko. Restart (stop - start) by na toto měl pomoci.

**Comment by PetrKotynek** [comment]
Nepovedlo sem mi to zopakovat
