### ISSUE TITLE
Nelze načíst zvukové soubory v importu na Inovatice ani u nás na testu

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1590]
1. Nelze vyzkoušet import zvukových souborů - hlásí chybu jak u složky 81515, tak u složky NMCMH04771-ML00546. Zřejmě tam chybí nějaké soubory. Prosím @SykoraLukas  - podíváš se na to?

2. Michal u nás na testovací PA nasadil novou verzi a tam to při importu zvuku vyhodí tuto hlášku:

/home/proarc/.proarc/users/vojirovk/import/1-2_SV_11631/proarc_import/1-2_SV_11631_NMMLP00075-01-CO.foxml
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at sun.java2d.pipe.DrawImage.makeBufferedImage(DrawImage.java:348)
	at sun.java2d.pipe.DrawImage.renderImageXform(DrawImage.java:462)
	at sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:264)
	at sun.java2d.pipe.DrawImage.scaleImage(DrawImage.java:124)
	at sun.java2d.pipe.DrawImage.scaleImage(DrawImage.java:1050)
	at sun.java2d.pipe.ValidatePipe.scaleImage(ValidatePipe.java:207)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3281)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3221)
	at cz.incad.imgsupport.ImageSupport.getScaledInstanceJava2D(ImageSupport.java:320)
	at cz.incad.imgsupport.ImageSupport.scale(ImageSupport.java:252)
	at cz.cas.lib.proarc.common.imports.TiffImporter.scale(TiffImporter.java:611)
	at cz.cas.lib.proarc.common.imports.TiffImporter.createImages(TiffImporter.java:492)
	at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:109)
	at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSet(SoundRecordingImport.java:123)
	at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSets(SoundRecordingImport.java:104)
	at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.start(SoundRecordingImport.java:90)
	at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:259)
	at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:230)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

A to jak při importu nově zpracovaných souborů, tak při importu souborů, které už jsme vloni zpracovávali v PA ostrém.
Díky

**Comment by SykoraLukas** [comment]
Ten váš je o tom, že tam máte nastavenou malou paměť. Po zvýšení paměti již nebude problém.

U nás je chyba v konfiguraci, opravím.

**Comment by SykoraLukas** [comment]
Chyba je na základě kterého z těch dvou bodů?

**Comment by katerinasirova** [comment]
Na základě druhého, až opravíš u vás, dej vědět. Klidně label odstraň, jestli to není chyba :-)
U nás se domluvím s Michalem, aby byla zvýšená paměť. Na ostrém už zvýšení proběhlo, ale teď jsem nechtěla tuhle verzi nasazovat rovnou na ostrý. 
Díky

**Comment by svetlym** [comment]
> Ten váš je o tom, že tam máte nastavenou malou paměť. Po zvýšení paměti již nebude problém.

Zdravím,

řeč je o velikosti RAMky přidělený virtuálu, nebo o nastavení parametrů Javy při spouštění? Pokud je to to druhý, tak stejnej problém jste řešili u nás na ostrym Proarcu, bohužel ale nevím, jak jste to udělali.

**Comment by SykoraLukas** [comment]
Probl0mem je nastavení parametrů Javy při spouštění tomcatu. Můžete te budto opsat z konfigurace ostrého serveru nebo se řídit tímto [manuálem](https://www.labkey.org/Documentation/wiki-page.view?name=configwebappmemory)

**Comment by svetlym** [comment]
Děkuju za návod, pomohlo to.

PS: Nemůžu zavřít issue, protože jsem ji neotevíral já, tak prosím o zavření.

**Comment by SykoraLukas** [comment]
Jakmile upravím konfiguraci, tak přerhodim label na @katerinasirova ať si to otestuje.

**Comment by svetlym** [comment]
Už mi to taky došlo, proto jsem ten komentář smazal.

**Comment by SykoraLukas** [comment]
Díky, ale to jste nemusel.

@katerinasirova já si toho nejříve nevšiml, ale načítala jsi to pod špatným profilem. Pokud zadáš profil zvuk tak import projde. 
<img width="1576" alt="image" src="https://github.com/proarc/proarc/assets/27210823/cae2d83a-4b4f-4af3-b6fa-541c05f41a4f">

**Comment by katerinasirova** [comment]
Otestováno, už funguje - ono nešlo importovat ani jedním způsobem, resp. tuhle dávku jsem znovu spustila z přehledu dávek a dala jsem import zvukového souboru.

**Comment by ZdenkaSera** [comment]
@katerinasirova Tady bych nechala zavření na Vás. Díky.
