### ISSUE TITLE
Akubra / Chyba exportu NDK čísla s eČlánky

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1613]
Na testovacím systému s Akubrou (Verze: 4.0.7-DEV) se mi nedaří exportovat NDK Číslo, které obsahuje eČlánky. Exporty eMonografií, CEJSH i Crossref jinak fungují.

Chyba:
```
java.lang.IllegalArgumentException: Malformed object token: http://local.fedora.server/fedora/get/icon:application_pdf/PREVIEW
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.getBlobId(AkubraLowlevelStorage.java:592)
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieve(AkubraLowlevelStorage.java:412)
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieveDatastream(AkubraLowlevelStorage.java:166)
	at cz.incad.kramerius.fedora.om.impl.AkubraDOManager.retrieveDatastream(AkubraDOManager.java:225)
	at cz.cas.lib.proarc.common.fedora.akubra.AkubraUtils.getDigitalObjectToExport(AkubraUtils.java:128)
	at cz.cas.lib.proarc.common.export.Kramerius4Export.exportPid(Kramerius4Export.java:519)
	at cz.cas.lib.proarc.common.export.Kramerius4Export.export(Kramerius4Export.java:218)
	at cz.cas.lib.proarc.common.export.ExportProcess.krameriusExport(ExportProcess.java:566)
	at cz.cas.lib.proarc.common.export.ExportProcess.start(ExportProcess.java:143)
	at cz.cas.lib.proarc.common.export.ExportProcess.run(ExportProcess.java:122)
	at cz.cas.lib.proarc.common.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.fcrepo.server.errors.MalformedPidException: PID object-id cannot contain '/' character.
	at org.fcrepo.common.PID.normalize(PID.java:175)
	at org.fcrepo.common.PID.normalize(PID.java:119)
	at org.fcrepo.common.PID.<init>(PID.java:69)
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.getBlobId(AkubraLowlevelStorage.java:579)
	... 15 more
```

**Comment by PetrKotynek** [comment]
[pa_conf.zip](https://github.com/proarc/proarc/files/12680464/pa_conf.zip)

konfigurace PA testovaciho stroje PK

**Comment by SykoraLukas** [comment]
Opraveno, k testu na Akubře.

**Comment by kerschfilip** [comment]
Funguje, děkuji!

**Comment by kerschfilip** [comment]
Otestováno znovu na `Verze:4.1.1-SNAPSHOT`, funguje, zavírám
