### ISSUE TITLE
Nelze exportovat archivní balíček pro eMonografie (v4.1.1)

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1645]
Ve verzi 4.1.1 se mi nedaří exportovat archivní balíček pro svazek NDK eMonografie. Testováno na Inovatice i v KNAV. Ve správě procesů je chyba:

```
java.lang.IllegalArgumentException: Unsupported type of package
	at cz.cas.lib.proarc.common.process.export.ExportProcess.archiveExport(ExportProcess.java:248)
	at cz.cas.lib.proarc.common.process.export.ExportProcess.start(ExportProcess.java:164)
	at cz.cas.lib.proarc.common.process.export.ExportProcess.run(ExportProcess.java:130)
	at cz.cas.lib.proarc.common.process.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ZdenkaSera** [comment]
@SykoraLukas  Prosím, tady přece jen prio. Díky.

**Comment by kerschfilip** [comment]
ve verzi 4.1.2 funguje na Akubře i Fedoře. Díky!
