### ISSUE TITLE
Archivní balíček eMonografie z Akubry nelze importovat zpět

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1663]
Archivní balíček eMonografie vytvořený ve verzi 4.1.3 na Akubře se mi nedaří po smazání importovat zpět ani do jiné instance 4.1.3 na Fedoře:

**1) Import do Akubry:**
- vytvořil jsem eMonografii
- exportoval archivní balíček
- smazal data z ProArcu
- importoval archivní balíček zpět přes profil archivace
chyba ukládání:
```
java.lang.NullPointerException
	at cz.cas.lib.proarc.common.storage.akubra.AkubraStorage.processStreams(AkubraStorage.java:217)
	at cz.cas.lib.proarc.common.storage.akubra.AkubraStorage.ingest(AkubraStorage.java:202)
	at cz.cas.lib.proarc.common.storage.akubra.AkubraImport.importItemImpl(AkubraImport.java:414)
	at cz.cas.lib.proarc.common.storage.akubra.AkubraImport.importItem(AkubraImport.java:291)
	at cz.cas.lib.proarc.common.storage.akubra.AkubraImport.importItems(AkubraImport.java:237)
	at cz.cas.lib.proarc.common.storage.akubra.AkubraImport.importBatch(AkubraImport.java:114)
	at cz.cas.lib.proarc.common.process.imports.archive.ArchiveImport.ingest(ArchiveImport.java:140)
	at cz.cas.lib.proarc.common.process.imports.archive.ArchiveImport.start(ArchiveImport.java:65)
	at cz.cas.lib.proarc.common.process.imports.ImportProcess.start(ImportProcess.java:263)
	at cz.cas.lib.proarc.common.process.imports.ImportProcess.run(ImportProcess.java:234)
	at cz.cas.lib.proarc.common.process.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.process.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```  

**2) Import do Fedory:**
- vytvořil jsem eMonografii na instanci PA na Akubře
- exportoval archivní balíček
- importoval archivní balíček do jiné instance 4.1.3 na Fedoře
chyba ukládání:
```
z.cas.lib.proarc.common.storage.DigitalObjectException: PID: uuid:eda88b63-4e8d-4cdd-a76b-217491c18d91
	at cz.cas.lib.proarc.common.storage.fedora.FedoraStorage.ingest(FedoraStorage.java:161)
	at cz.cas.lib.proarc.common.process.imports.FedoraImport.importItemImpl(FedoraImport.java:404)
	at cz.cas.lib.proarc.common.process.imports.FedoraImport.importItem(FedoraImport.java:284)
	at cz.cas.lib.proarc.common.process.imports.FedoraImport.importItems(FedoraImport.java:230)
	at cz.cas.lib.proarc.common.process.imports.FedoraImport.importBatch(FedoraImport.java:114)
	at cz.cas.lib.proarc.common.process.imports.archive.ArchiveImport.ingest(ArchiveImport.java:136)
	at cz.cas.lib.proarc.common.process.imports.archive.ArchiveImport.start(ArchiveImport.java:65)
	at cz.cas.lib.proarc.common.process.imports.ImportProcess.start(ImportProcess.java:263)
	at cz.cas.lib.proarc.common.process.imports.ImportProcess.run(ImportProcess.java:234)
	at cz.cas.lib.proarc.common.process.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cz.cas.lib.proarc.common.process.imports.ImportDispatcher$PriorityFuture.run(ImportDispatcher.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.yourmediashelf.fedora.client.FedoraClientException: HTTP 400 Error: <?xml version="1.0" encoding="UTF-8"?><management:validation  xmlns:management="http://www.fedora.info/definitions/1/0/management/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fedora.info/definitions/1/0/management/ http://www.fedora.info/definitions/1/0/validation.xsd" pid="unknown"  valid="true">
  <management:contentModels>
  </management:contentModels>
  <management:problems>
    <management:problem><?xml version="1.0" encoding="UTF-8"?>
<RESULT xmlns:foxml="info:fedora/fedora-system:def/foxml#"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <datastream xmlns="info:fedora/fedora-system:def/foxml#">
      <ASSERT xmlns="">Datastream must have a datastream id. (foxml:datastream: value of ID is missing)</ASSERT>
      <ASSERT xmlns="">Datastream control group type must be "E" for External-Ref, "M" for Managed-Content, "R" for Redirected, or "X" for Inline-XML-Metadata. (foxml:datastream: CONTROL_GROUP)</ASSERT>
   </datastream>
</RESULT></management:problem>
  </management:problems>
  <management:datastreamProblems>
  </management:datastreamProblems>
</management:validation>
	at com.yourmediashelf.fedora.client.response.FedoraResponseImpl.<init>(FedoraResponseImpl.java:72)
	at com.yourmediashelf.fedora.client.response.IngestResponse.<init>(IngestResponse.java:41)
	at com.yourmediashelf.fedora.client.request.Ingest.execute(Ingest.java:230)
	at cz.cas.lib.proarc.common.storage.fedora.FedoraStorage.ingest(FedoraStorage.java:154)
	... 15 more
```  

Při importu NDK PSP místo Archivace se ale problém neobjevuje

**Comment by SykoraLukas** [comment]
Prosím o zaslání balíčku na e-mail.

**Comment by kerschfilip** [comment]
Otestováno na 4.1.6, na problém už jsem nenarazil.

Děkuju!
