### ISSUE TITLE
Chyba při exportu zvukových dokumentů

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1736]
Zdravím,

nedaří se nám vyexportovat několik zvukových dokumentů.

Klient ukazuje exception:

```
cz.cas.lib.proarc.common.storage.DigitalObjectException: PID: null, Java
heap space
    at
cz.cas.lib.proarc.common.process.export.Kramerius4Export.export(Kramerius4Export.java:326)
    at
cz.cas.lib.proarc.common.process.export.ExportProcess.krameriusExport(ExportProcess.java:802)
    at
cz.cas.lib.proarc.common.process.export.ExportProcess.start(ExportProcess.java:158)
    at
cz.cas.lib.proarc.common.process.export.ExportProcess.run(ExportProcess.java:133)
    at
cz.cas.lib.proarc.common.process.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
```

V logu Tomcatu jsou ale jen warningy:

```
INFO: Server startup in 54826 ms
Dec 11, 2024 8:23:39 AM cz.cas.lib.proarc.common.actions.ChangeModels changeMode
lsAndRepairMetadata
WARNING: Object changed from model:page to model:ndkpage succesfully. Total item
s (4).
Dec 11, 2024 10:47:35 AM cz.cas.lib.proarc.common.actions.ChangeModels changeMod
elsAndRepairMetadata
WARNING: Object changed from model:page to model:ndkpage succesfully. Total item
s (4).
Dec 11, 2024 11:09:07 AM cz.cas.lib.proarc.common.actions.ChangeModels changeMod
elsAndRepairMetadata
WARNING: Object changed from model:page to model:ndkpage succesfully. Total item
s (4).
```

Paměť pro Javu máme přidělenou takhle:

```
Environment="CATALINA_OPTS=-Xms6144m -Xmx8192m -server -XX:+UseParallelGC"
```

Docela mě mate, že chybu zobrazí jen klient, v logu není. Nedostatek paměti by ale dával smysl, nastává to jen u některejch zvukovejch dokumentů. Napadá vás nějaký jiný řešení než opět navýšit paměť pro Javu?

**Comment by svetlym** [comment]
Podle správy procesů žádný jiný procesy dneska nikdo nepouštěl.

Verzi máme 4.2.3-SNAPSHOT.

Na strukturu balíčku musí odpovědět @katerinasirova.

**Comment by katerinasirova** [comment]
Ahoj, padají všechny typy struktur - t.j. ZD se skladbami a pod nimi zvukový soubor (typ 1), ZD se skladbami a částmi skladeb a pod nimi zvukový soubor (typ 2). A naopak se mezi několik balíčky, které se neexportovaly, vyexportovaly dva, každý s jinou strukturou (typ 1 i typ 2). Právě jsem v tom nenašla žádnou logiku. 
Prosím mrkni nám na to, ať už si můžeme ten letošní VISK odškrtnout. Díky

**Comment by SykoraLukas** [comment]
A jakou mají velikost soubory, které jsou importovány?

**Comment by SykoraLukas** [comment]
Nejjednodušší řešení je zvýšit paměť. Případně mi tento balíček pošli a zkusím zjistit, kde by se dalo optimalizovat, aby nebylo potřeba takové paměti.

**Comment by katerinasirova** [comment]
Dobře, díky. Předám Michalovi a balíček pošlu, u těch gramodesek a obecně zvukových souborů budou ta archivní data týkající se jedné strany opravdu velká.

**Comment by katerinasirova** [comment]
V MKP nám navýšili paměť o 6 GB a na většinu desek to pomohlo, zůstává mi tam ale jedna, kterou nelze exportovat, hlásí mi to chybu
```
cz.cas.lib.proarc.common.storage.DigitalObjectException: PID: null, Requested array size exceeds VM limit
	at cz.cas.lib.proarc.common.process.export.Kramerius4Export.export(Kramerius4Export.java:326)
	at cz.cas.lib.proarc.common.process.export.ExportProcess.krameriusExport(ExportProcess.java:802)
	at cz.cas.lib.proarc.common.process.export.ExportProcess.start(ExportProcess.java:158)
	at cz.cas.lib.proarc.common.process.export.ExportProcess.run(ExportProcess.java:133)
	at cz.cas.lib.proarc.common.process.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
Odkaz na stažení balíčku: https://drive.google.com/drive/folders/1paTuI2GH2XOawmfPUMgKMxFsb_qzMMNR?usp=sharing

Jinak NDK PSP export stejného balíčku proběhl bez problémů.

Prosím, mohl by ses na to @SykoraLukas podívat? Díky moc.

**Comment by SykoraLukas** [comment]
Jak máte nastaveny následující property v konfigu?

export.kramerius4.excludeDatastreamId=AUDIT, RAW, PRIVATE_NOTE, NDK_ARCHIVAL, NDK_USER, NDK_ARCHIVAL_MIX, RAW_MIX, NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC, SOURCE

Ideálně by tam mělo být vyjmenováno právě NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC a SOURCE, protože to jsou věci, které nejsou potřebné pro Krameria. Hlavně tam nesmí být zmíněno NDK_AUDIO_USER, které je potřeba pro přehrávání z Krameria.

Jaké jsou tedy hw prostředky paměti na serveru a jak vypadá rozsah ve spousteném scriptu? 
`Environment="CATALINA_OPTS=-Xms2048m -Xmx28672m -server -XX:+UseParallelGC"`

**Comment by svetlym** [comment]
> Jak máte nastaveny následující property v konfigu?
> 
> export.kramerius4.excludeDatastreamId=AUDIT, RAW, PRIVATE_NOTE, NDK_ARCHIVAL, NDK_USER, NDK_ARCHIVAL_MIX, RAW_MIX, NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC, SOURCE

```# list datastreams to exclude from export
export.kramerius4.excludeDatastreamId=AUDIT, RAW, PRIVATE_NOTE, NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC```

> Ideálně by tam mělo být vyjmenováno právě NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC a SOURCE, protože to jsou věci, které nejsou potřebné pro Krameria. Hlavně tam nesmí být zmíněno NDK_AUDIO_USER, které je potřeba pro přehrávání z Krameria.

SOURCE jsem doplnil, vyzkoušíme.

> Jaké jsou tedy hw prostředky paměti na serveru a jak vypadá rozsah ve spousteném scriptu? `Environment="CATALINA_OPTS=-Xms2048m -Xmx28672m -server -XX:+UseParallelGC"`

Server má teď přiděleno 16 GB.

```Environment="CATALINA_OPTS=-Xms6g -Xmx16g -server -XX:+UseParallelGC"```

**Comment by svetlym** [comment]
Zrovna se o tom bavíme a Katku napadla ještě jedna možnost: Neinlinovat zvukový data do FOXML, místo toho je nahrát na audioserver a do FOXML dát jen odkazy.

**Comment by svetlym** [comment]
> > Ideálně by tam mělo být vyjmenováno právě NDK_AUDIO_ARCHIVAL, NDK_AUDIO_ARCHIVAL_FLAC a SOURCE, protože to jsou věci, které nejsou potřebné pro Krameria. Hlavně tam nesmí být zmíněno NDK_AUDIO_USER, které je potřeba pro přehrávání z Krameria.
> 
> SOURCE jsem doplnil, vyzkoušíme.

Vyzkoušeli jsme, nepomohlo to.

**Comment by SykoraLukas** [comment]
> Zrovna se o tom bavíme a Katku napadla ještě jedna možnost: Neinlinovat zvukový data do FOXML, místo toho je nahrát na audioserver a do FOXML dát jen odkazy.

Spíše bych zkusil cestu vyexportovat do exportního adresáře jako samostatný soubor. A ve FOXML na tento soubor jen linkovat.

**Comment by SykoraLukas** [comment]
Mám opraveno. Bude v příští verzi.

Vyřešeno tím způsobem, že jsem u zvukáčů ustoupil od toho, aby výsledné FOXML připravila FEDORA, místo toho si ho skládám sám jen z datastreamů, které opravdu jsou potřeba pro Krameria.

**Comment by katerinasirova** [comment]
Super, díky. Mimochodem bychom měli počítat i s možností využití "audioserveru", takže tvůj návrh "cestu vyexportovat do exportního adresáře jako samostatný soubor a ve FOXML na tento soubor jen linkovat" bychom neměli zapomenout. Můžeme se o tom pobavit na schůzce.

**Comment by kerschfilip** [comment]
Podle info ze schůzky 1. 9. 2026 by měl být problém vyřešen. Možnost exportovat soubory do vlastní složky a ve FOXML na ně linkovat je zaznamenán jako rozvojový návrh zde: https://github.com/proarc/proarc/issues/1906
