### ISSUE TITLE
NPE při nevalidním workflow.xml

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#439]
Od @lucka-pavlova: Při nevalidním workflow.xml systém hlásí "Neočekávaná chyba".

proarc.2016-02-16.log:
```
java.lang.NullPointerException
        at cz.cas.lib.proarc.common.workflow.TaskManager.sortJobTaskByBlockers(TaskManager.java:109)
        at cz.cas.lib.proarc.common.workflow.TaskManager.findTask(TaskManager.java:97)
        at cz.cas.lib.proarc.webapp.server.rest.WorkflowResource.getTask(WorkflowResource.java:260)
```

**Comment by pokorsky** [comment]
Opraveno.
