### ISSUE TITLE
crossref: Chybné XSLT pro MODS name a dateIssued

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#450]
Při pokusu o export do CrossRefu se mi objeví chyba:
Nothing to export!
Konkrétně jsem to zkoušela na titulu Knihy a dějiny v instalaci proarc-ozc. Zkoušela jsem vyexportovat všechny možné úrovně a všude byla stejná chyba.

**Comment by pokorsky** [comment]
Na proarc-ozc nemám přístup. Z popisu nelze problém určit. Nejspíš exportovaná hierarchie neobsahuje žádný e-článek.

**Comment by slapakovai** [comment]
Zkoušela jsem exportovat Knihy a dějiny, které nemají úroveň čísla, ečlánky tam jsou. Jde to nějak opravit, aby nebyla vyžadována úroveň čísla nebo ročníku, pokud ji časopis nemá?

**Comment by slapakovai** [comment]
Teď jsem ještě zkoušela časopis Slovo a slovesnost, tam jsou tyto chyby:

Column:18 Line:20 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:20 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:22 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:22 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:52 Line:34 cvc-datatype-valid.1.2.1: '' is not a valid value for 'NMTOKEN'.
Column:52 Line:34 cvc-attribute.3: The value '' of attribute 'contributor_role' on element 'person_name' is not valid with respect to its type, '#AnonType_contributor_rolecontributor.atts'.
Column:52 Line:34 cvc-complex-type.2.4.b: The content of element 'person_name' is not complete. One of '{"http://www.crossref.org/schema/4.3.6":given_name, "http://www.crossref.org/schema/4.3.6":surname}' is expected.
Column:18 Line:37 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:37 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:39 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:39 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:42 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:62 Line:45 cvc-enumeration-valid: Value 'mul' is not facet-valid with respect to enumeration '[aa, ab, af, am, ar, as, ay, az, ba, be, bg, bh, bi, bn, bo, br, ca, co, cs, cy, da, de, dz, el, en, eo, es, et, eu, fa, fi, fj, fo, fr, fy, ga, gd, gl, gn, gu, ha, he, hi, hr, hu, hy, ia, id, ie, ik, is, it, ja, jw, ka, kk, kl, km, kn, ko, ks, ku, ky, la, ln, lo, lt, lv, mg, mi, mk, ml, mn, mo, mr, ms, mt, my, na, ne, nl, no, oc, om, or, pa, pl, ps, pt, qu, rm, rn, ro, ru, rw, sa, sd, sg, si, sk, sl, sm, sn, so, sq, sr, ss, st, su, sv, sw, ta, te, tg, th, ti, tk, tl, tn, to, tr, ts, tt, tw, uk, ur, uz, vi, vo, wo, xh, yi, yo, zh, zu]'. It must be a value from the enumeration.
Column:62 Line:45 cvc-attribute.3: The value 'mul' of attribute 'language' on element 'journal_article' is not valid with respect to its type, '#AnonType_languagelanguage.atts'.
Column:52 Line:50 cvc-datatype-valid.1.2.1: '' is not a valid value for 'NMTOKEN'.
Column:52 Line:50 cvc-attribute.3: The value '' of attribute 'contributor_role' on element 'person_name' is not valid with respect to its type, '#AnonType_contributor_rolecontributor.atts'.
Column:52 Line:50 cvc-complex-type.2.4.b: The content of element 'person_name' is not complete. One of '{"http://www.crossref.org/schema/4.3.6":given_name, "http://www.crossref.org/schema/4.3.6":surname}' is expected.
Column:18 Line:53 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:53 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:55 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:55 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:62 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:18 Line:77 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:77 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:79 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:79 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:86 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:18 Line:100 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:100 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:102 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:102 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:109 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:18 Line:123 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:123 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:125 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:125 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:132 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:15 Line:146 cvc-complex-type.2.4.b: The content of element 'person_name' is not complete. One of '{"http://www.crossref.org/schema/4.3.6":surname}' is expected.
Column:18 Line:149 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:149 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:151 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:151 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:158 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:51 Line:166 cvc-datatype-valid.1.2.1: '' is not a valid value for 'NMTOKEN'.
Column:51 Line:166 cvc-attribute.3: The value '' of attribute 'contributor_role' on element 'person_name' is not valid with respect to its type, '#AnonType_contributor_rolecontributor.atts'.
Column:18 Line:172 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:172 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:174 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:174 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:181 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:51 Line:189 cvc-datatype-valid.1.2.1: '' is not a valid value for 'NMTOKEN'.
Column:51 Line:189 cvc-attribute.3: The value '' of attribute 'contributor_role' on element 'person_name' is not valid with respect to its type, '#AnonType_contributor_rolecontributor.atts'.
Column:18 Line:195 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:195 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:197 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:197 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:204 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
Column:52 Line:212 cvc-datatype-valid.1.2.1: '' is not a valid value for 'NMTOKEN'.
Column:52 Line:212 cvc-attribute.3: The value '' of attribute 'contributor_role' on element 'person_name' is not valid with respect to its type, '#AnonType_contributor_rolecontributor.atts'.
Column:52 Line:212 cvc-complex-type.2.4.b: The content of element 'person_name' is not complete. One of '{"http://www.crossref.org/schema/4.3.6":given_name, "http://www.crossref.org/schema/4.3.6":surname}' is expected.
Column:18 Line:215 cvc-datatype-valid.1.2.1: '3.' is not a valid value for 'integer'.
Column:18 Line:215 cvc-type.3.1.3: The value '3.' of element 'month' is not valid.
Column:18 Line:217 cvc-datatype-valid.1.2.1: '17.0' is not a valid value for 'integer'.
Column:18 Line:217 cvc-type.3.1.3: The value '17.0' of element 'year' is not valid.
Column:11 Line:224 cvc-complex-type.2.4.a: Invalid content was found starting with element 'resource'. One of '{"http://www.crossref.org/schema/4.3.6":doi}' is expected.
cz.cas.lib.proarc.common.export.ExportException: Validation errors!
	at cz.cas.lib.proarc.common.export.crossref.CrossrefBuilder.createPackage(CrossrefBuilder.java:157)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportPackage(CrossrefExport.java:107)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportImpl(CrossrefExport.java:77)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.export(CrossrefExport.java:48)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newCrossrefExport(ExportResource.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:662)

Můžeš mi prosím poradit, co s tím?

**Comment by pokorsky** [comment]
Toto je výstup závěrečné validace metadat balíku podle crossref schema. Nejsem si jistý, že je to způsobeno chybějícím ročníkem, protože to je detekováno.

Zadání z issue #444 ani XSL [šablona](https://drive.google.com/drive/folders/0B_ZKc3E0bVyVVVlUZ28xdkczZmc) dodaná KNAV s chybějícími ročníky a čísly nepočítá. Je tedy potřeba nejdříve specifikovat jaké hodnoty se mají v takovém případě šabloně předat nebo co má šablona v takovém případě generovat.

Určitě by pomohlo založit část té hierarchie na testovacím serveru.

**Comment by melichova** [comment]
Hierarchie časopisů "Knihy a dějiny" a "Slovo a slovesnost" založena v testovacím ProArcu.

**Comment by pokorsky** [comment]
"Slovo a slovesnost" nenalezeno. "Knihy a dějiny" založeno jako K4 periodikum. Zadání crossref předpokládalo NDK hierarchii pokud si dobře pamatuji. Jinak na proarc-test.libj je pouze verze 2.1.

**Comment by pokorsky** [comment]
Omlouvám se. Připojil jsem se na jiný port. Periodika jsem už našel.

**Comment by pokorsky** [comment]
Pokud jde o "Slovo a slovesnost", tak většina chyb je způsobena chybným formátem data. Číslo obsahuje datum 17.03.2016, ale [šablona](https://github.com/proarc/proarc/blob/19c5f2baf701e4342f03e49941881680ba99de8c/proarc-common/src/main/resources/cz/cas/lib/proarc/common/export/crossref/mods_crossref.xsl) dodaná od @pavelkam očekává formát yyyymmdd.
Další chyby jsou způsobeny prázdnými elementy `/mods/name` v MODS eČlánků se kterými šablona nepočítá. Výsledkem je nevalidní `<person_name sequence="first" contributor_role=""/>`.

Šablonu lze upravit a testovat v `webapps/proarc/WEB-INF/classes/cz/cas/lib/proarc/common/export/crossref`, viz. proarc.war.

**Comment by pavelkam** [comment]
Na google drive a testovací server jsem nahrál upravenou šablonu. Nově počítá s chybějící úrovní issue nebo volume a se správným formátem data DD.MM.RRRR. Pokud v hierarchii chybí úroveň issue, měl by se vstupní parametr publication_date předávat z úrovně volume. 

Co se týká MODS name, narazil jsem na problém, že šablona funguje u mě při transformaci v php, ale v proarcu hází prázdný element contributors. Testuju to v obou případech na stejných MODSech ze Slovo a slovesnost z testovacího serveru. Zdá se jako by každý procesor jinak vyhodnotil funkci key(). Jde tam o to, že pro crossref formát se vybírají jen autoři s rolí aut, edt, rev nebo trl. Navíc to grupuju podle uuid článku, protože počáteční definice key() pracuje nad celým modsCollection. 
Nenapadlo by tě co s tím?

**Comment by pavelkam** [comment]
Tak  /mods/name elementy vyřešeny, export Slova a slovesnosti na testovacím serveru probíhá v pořádku.
Pokud jsou články řazeny přímo pod úroveň ročníku, jako tady u Knihy a dějiny, měl by být při jejich exportu parametr "issue" pro šablonu prázdný a parametr "publication_date" předaný z úrovně ročníku. 
Pokud by v hierarchii chyběla úroveň ročníku, bude při exportu prázdný předávaný parametr "volume".

**Comment by slapakovai** [comment]
Export článků z periodika, který nemá úroveň číslo, stále nefunguje. Takže znovu otevírám tohle issue a prosím o opravu podle diskuze výše.

**Comment by pokorsky** [comment]
Tohle už je dávno vydaná verze. Založ prosím novou issue.
