### ISSUE TITLE
Tomcat 8: chybná classpath pro Z39.50

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#514]
Hází to neočekávanou chybu, použila jsem konkrétně čárový kód 26000003808 a 26000004510, ale asi je to jedno, nejde to na ničem. Nejdnou ani periodika z katalogu Periodik ani podle kódu ani podle signatury.

**Comment by pokorsky** [comment]
Neuvádíte žádnou chybovou hlášku. Kontaktujte prosím svého administrátora. Nejspíš je problém v konfiguraci. Na testovacím serveru katalog funguje. První čárový kód ale vrátí prázdný záznam, druhý je v pořádku.

**Comment by mduda100871** [comment]
Aktualne tam bezi posledni verze ProArcu, fedora 3.8.1 a JDK 8 (1.8.0_112-b15), v logu se objevuje nasledujici vyjimka (zrejme problem s prasovanim xml):


...
18-Jan-2017 10:27:13.178 SEVERE [ajp-bio-127.0.0.1-8009-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Jersey Web Application] in context with path [/proarc] threw exception [org.springframewo
rk.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [z3950/Z3950ApplicationContext.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'compon
ent-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher] with root cause
 java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher
        at org.springframework.context.config.ContextNamespaceHandler$1.parse(ContextNamespaceHandler.java:64)
        at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:69)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1246)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1236)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:133)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:90)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:468)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:363)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:313)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:290)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:142)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:158)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:184)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:112)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:79)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:97)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:411)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:338)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:122)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:66)
        at cz.cas.lib.proarc.z3950.Z3950Client.<init>(Z3950Client.java:74)
        at cz.cas.lib.proarc.common.catalog.Z3950Catalog.<init>(Z3950Catalog.java:124)
        at cz.cas.lib.proarc.common.catalog.Z3950Catalog.get(Z3950Catalog.java:107)
        at cz.cas.lib.proarc.common.config.Catalogs.findCatalog(Catalogs.java:84)
        at cz.cas.lib.proarc.webapp.server.rest.BibliographicCatalogResource.find(BibliographicCatalogResource.java:109)
        at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
        at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
...

**Comment by pokorsky** [comment]
Martine to vypadá na další problém s classpath Tomcatu 8 jako v případě issue #477. V tomto případě je potřeba zařídit, aby `spring-2.5.jar` byl na konci classpath nebo alespoň za `proarc-z3950-*-SNAPSHOT.jar`.

Důvodem je mizející podpora protokolu Z39.50. Vývoj knihovny jzkit_z3950_plugin byl ukončen bez náhrady.

**Comment by mduda100871** [comment]
Ahoj,

muzu ty jary zkusit vytahnout z war balicku "natvrdo" (rozbalim, smazu a znovu zabalim) a presunout do externiho adresare ~/lib a pak uz to ridit promennou prostredi CLASSPATH shellu?

MD

**Comment by mduda100871** [comment]
BTW - k tomu ukonceni podpory z3950 knihovny...to neni moc dobra zprava. Nemeli bychom tedy uvazovat nad jinou cestou? Treba se pokusit vyuzit REST-API Alephu pro stahovani zaznamu?

MD

**Comment by pokorsky** [comment]
Já myslím, že pořadí by mělo jít určit pomocí `PreResources` a `PostResources` v `context.xml`, tak jako v issue #477. Podle dokumentace se classpath pak složí v pořadí PreResources, MainResources, ClassResources, JarResources, PostResources. Definice `spring-2.5.jar` jako PostResources by mělo problém vyřešit. Můžeš to vyzkoušet?
```xml
<PostResources className="org.apache.catalina.webresources.FileResourceSet"
                base="${catalina.base}/webapps/proarc/WEB-INF/lib/spring-2.5.jar"
                webAppMount="/WEB-INF/lib/spring-2.5.jar" />
```
Pokud jde o protokol, tak ProArc podporuje [Aleph - XServer](https://github.com/proarc/proarc/wiki/Konfigurace#aleph---xserver).

**Comment by MartinRumanek** [comment]
V MEditoru na Z39.50 používám knihovnu yaz4j (http://www.indexdata.com/yaz4j), ale je nutné mít nainstalovanou na systému knihovnu libyaz

na Centos se nainstaluje tímto postupem:
```
vim /etc/yum.repos.d/indexdata.repo (obsah)
rpm --import http://ftp.indexdata.com/pub/yum/centos/7/RPM-GPG-KEY-indexdata
yum -y install libyaz5
```

**Comment by mduda100871** [comment]
hmm, tak uprava v context.xml nezabrala, porad pada stejna vyjimka :(

**Comment by mduda100871** [comment]
v Jessie je libyaz verze 4.2.

**Comment by mduda100871** [comment]
uz to funguje, obsah context.xml:
<?xml version="1.0" encoding="UTF-8"?>


<Context>

    <Resources>

        
        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar"
            webAppMount="/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar" />

        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/proarc-z3950-3.2.1.jar"
            webAppMount="/WEB-INF/lib/proarc-z3950-3.2.1.jar" />

        <PostResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/spring-2.5.jar"
            webAppMount="/WEB-INF/lib/spring-2.5.jar" />

    </Resources>

</Context>

**Comment by SmejkalovaAnna** [comment]
Uz to funguje, děkuji všem.

Anca




Dne 18.1.2017 v 16:33 pokorsky napsal(a):

**Comment by SmejkalovaAnna** [comment]
Resp. v Testovacim v KNAV to funguje...

anca





Dne 18.1.2017 v 16:33 pokorsky napsal(a):

**Comment by SmejkalovaAnna** [comment]
Pardon, omlouvam se, napsala jsem to na spatnej mejl, takze si oba  moje 
mejly smazte... omlouvam se



Dne 18.1.2017 v 16:33 pokorsky napsal(a):

**Comment by pokorsky** [comment]
Použití yaz4j bych se rád vyhnul kvůli platformní závislosti. Z webu není jasné jestli funguje s java 8. Poslední changelog je z 2015/05/22 na blogu zmiňují java 6. Zatím Z39.50 máme vyřešeno, ale do budoucna by bylo dobré na straně Alephu počítat s něčím nad HTTP.

**Comment by pokorsky** [comment]
@mduda100871:  Martine můžeš ještě zkusit variantu bez proarc-z3950-3.2.1.jar? Problém je to číslo verze. Bylo by jednodušší to tam nedávat.
```xml
<PostResources className="org.apache.catalina.webresources.JarResourceSet"
                base="${catalina.base}/webapps/proarc/WEB-INF/lib/spring-2.5.jar"
                webAppMount="/WEB-INF/classes" />
```

**Comment by mduda100871** [comment]
no to prave byla ta ma pred-predchozi reakce, ze i po uprave context.xml to nefunguje, teprve kdyz jsem upravil context.xml i s proarc-z3950-3.2.1.jar, tak to zacalo fungovat

**Comment by mduda100871** [comment]
...
ale do budoucna by bylo dobré na straně Alephu počítat s něčím nad HTTP.
...
https://developers.exlibrisgroup.com/aleph/apis/Aleph-RESTful-APIs

o tom jsem prave mluvil

**Comment by pokorsky** [comment]
Jen pro jistotu, zkoušel jsi tu poslední verzi s JarResourceSet a webAppMount? Původní návrh byl s FileResourceSet.

**Comment by mduda100871** [comment]
mas pravdu, s JarResourceSet jsem to nezkousel, takze az ted, ale bohuzel nefunguje to take:
...
<?xml version="1.0" encoding="UTF-8"?>


<Context>

    <Resources>

        
        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar"
            webAppMount="/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar" />

        <PostResources className="org.apache.catalina.webresources.JarResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/spring-2.5.jar"
            webAppMount="/WEB-INF/classes" />

        

    </Resources>

</Context>

...
20-Jan-2017 10:07:55.059 SEVERE [ajp-bio-127.0.0.1-9009-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Jersey Web Application] in context with path [/proarc] threw exception [org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [z3950/Z3950ApplicationContext.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher] with root cause
 java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher
        at org.springframework.context.config.ContextNamespaceHandler$1.parse(ContextNamespaceHandler.java:64)
        at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:69)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1246)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1236)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:133)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:90)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:468)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:363)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:313)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:290)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:142)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:158)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:184)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:112)
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:79)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:97)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:411)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:338)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:122)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:66)
        at cz.cas.lib.proarc.z3950.Z3950Client.<init>(Z3950Client.java:74)
        at cz.cas.lib.proarc.common.catalog.Z3950Catalog.<init>(Z3950Catalog.java:124)
        at cz.cas.lib.proarc.common.catalog.Z3950Catalog.get(Z3950Catalog.java:107)
        at cz.cas.lib.proarc.common.config.Catalogs.findCatalog(Catalogs.java:84)
        at cz.cas.lib.proarc.webapp.server.rest.BibliographicCatalogResource.find(BibliographicCatalogResource.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
        at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
...

**Comment by mduda100871** [comment]
tato konfigurace funguje:
<?xml version="1.0" encoding="UTF-8"?>


<Context>

    <Resources>

        
        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar"
            webAppMount="/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar" />

        

        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/proarc-z3950-3.2.1.jar"
            webAppMount="/WEB-INF/lib/proarc-z3950-3.2.1.jar" />

        <PostResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/spring-2.5.jar"
            webAppMount="/WEB-INF/lib/spring-2.5.jar" />

    </Resources>

</Context>

**Comment by mduda100871** [comment]
Ahoj,

uzavreme tuto issue s nastavenim, ktere jsem posilal, nebo se tim jeste budes zabyvat? 

MD

**Comment by pokorsky** [comment]
Je potřeba to přidat do context.xml  v ProArcu, aby s tím v budoucnu neměli problémy ostatní. Chtěl jsem se ještě podívat do zdrojáků Tomcatu, jestli se mi nepodaří zbavit té deklarace proarc-z3950-3.2.1.jar. Jinak bude potřeba přidat placeholder, aby se verze přepsala při každém buildu. Zatím jsem na to neměl čas a dočasné řešení funguje..

**Comment by mduda100871** [comment]
ok

**Comment by MartinRumanek** [comment]
> Použití yaz4j bych se rád vyhnul kvůli platformní závislosti. Z webu není jasné jestli funguje s java 8. Poslední changelog je z 2015/05/22 na blogu zmiňují java 6. 

S Javou 8 knihovna funguje, používám ji v MEditoru. 
Poslední commit mají z 1.4.2016 a v Travisu si kontrolují build i právě pro Javu 8.

Multiplatformní závislost tam je, ale je to stejné jako s knihovnou Kakadu (existuje binárka pro Linux, Windows i OSX).

>Zatím Z39.50 máme vyřešeno, ale do budoucna by bylo dobré na straně Alephu počítat s něčím nad HTTP.

Pozor, jsou i jiné katalogy, které používají binární protokol Z39.50.

**Comment by pokorsky** [comment]
Díky za užitečné informace. Pokud javová knihovna přestane fungovat, tak je yaz4j jasný kandidát.
