### ISSUE TITLE
Nelze importovat skener z archivačního balíku

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#519]
Pokud exportovaný archivační balík obsahuje odkaz (PID) na skener, který není součástí systému kam se importuje, skončí import s chybou. Je potřeba upravit DB model pro delší PID.

```
Caused by: java.lang.IllegalStateException: BatchItem{id=null, batchId=18, pid=device:60098dd7-21b9-417f-acc4-367cff61b127, dsId=null, file=proarc/import/Archive/archive_92d82187-55b8-4717-9330-6e92dc4e9b0d/92d82187-55b8-4717-9330-6e92dc4e9b0d/proarc_import/device_0001_60098dd7-21b9-417f-acc4-367cff61b127.xml, state=LOADING, type=OBJECT, log=null, timestamp=2017-01-25 19:29:29.073}
	at cz.cas.lib.proarc.common.imports.ImportBatchManager.addLocalObject(ImportBatchManager.java:354)
	at cz.cas.lib.proarc.common.export.archive.PackageReader$ImportSession.addObject(PackageReader.java:620)
	at cz.cas.lib.proarc.common.export.archive.PackageReader.processDevice(PackageReader.java:193)
	... 15 more
Caused by: org.apache.empire.db.exceptions.FieldValueTooLongException: The value supplied for field ![ProarcDatabase.PROARC_BATCH_ITEM.PID] is too long. The maximum number of characters is 41.
	at org.apache.empire.db.DBTableColumn.validate(DBTableColumn.java:409)
	at org.apache.empire.db.DBRecord.validateValue(DBRecord.java:619)
	at org.apache.empire.db.DBRecord.setValue(DBRecord.java:572)
	at org.apache.empire.db.DBRecord.setValue(DBRecord.java:590)
	at org.apache.empire.db.DBRecord.setBeanValue(DBRecord.java:994)
	at org.apache.empire.db.DBRecord.setBeanValues(DBRecord.java:1026)
	at org.apache.empire.db.DBRecord.setBeanValues(DBRecord.java:1038)
	at cz.cas.lib.proarc.common.dao.empiredb.EmpireBatchItemDao.update(EmpireBatchItemDao.java:58)
	at cz.cas.lib.proarc.common.imports.ImportBatchManager.addLocalObject(ImportBatchManager.java:349)
	... 17 more
```

**Comment by pokorsky** [comment]
Vyřešeno.
