### ISSUE TITLE
3.4-shapshot java.lang.IllegalStateException

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#653]
V logu verze 3.4-snapshot jsem narazil na následující opakující se výpis exceptiony:

```
Nov 15, 2017 10:28:49 AM cz.cas.lib.proarc.authentication.proarc.ProArcAuthenticator authenticate
SEVERE: kortism
java.lang.IllegalStateException: java.sql.SQLException: Already closed.
	at cz.cas.lib.proarc.common.dao.empiredb.SqlTransaction.close(SqlTransaction.java:64)
	at cz.cas.lib.proarc.common.user.UserManagerSql.authenticate(UserManagerSql.java:74)
	at cz.cas.lib.proarc.authentication.proarc.ProArcAuthenticator.authenticate(ProArcAuthenticator.java:48)
	at cz.cas.lib.proarc.authentication.ChainAuthenticator.authenticate(ChainAuthenticator.java:52)
	at cz.cas.lib.proarc.authentication.ProarcHTTPServlet.doPost(ProarcHTTPServlet.java:57)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:79)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Already closed.
	at org.apache.tomcat.dbcp.dbcp.PoolableConnection.close(PoolableConnection.java:114)
	at org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
	at cz.cas.lib.proarc.common.dao.empiredb.SqlTransaction.close(SqlTransaction.java:62)
	... 33 more
 
```

Nevím, co ho vyvolává, uživatele zmíněného v logu tu dneska nemám. V proarcu současně pracuje i někdo jiný, všechny errory se ale týkají stejného uživatele.

**Comment by MartinRumanek** [comment]
Z toho bohužel moc nepoznám, dříve jste podobné chování nepozoroval? Je to skutečně způsobené novou verzí?

Je něco zajímavého v access logu Tomcatu?

**Comment by svetlym** [comment]
Novou verzí to být nemusí. Sice jsem na tuhle chybu narazil poprvé, na druhou stranu jsme ale teprve minulý měsíc dělal upgrade ostré verze proarcu z 2.1 na 3.2 (plus upgrade fedory na 3.0), takže to klidně může souviset s tím.

Zbylé logy jsem si bohužel smazal. Budu to určitě dál sledovat - dám vědět, když se to bude opakovat.

**Comment by svetlym** [comment]
Přikládám nové logy z provozu verze 3.4-snapshot.

illegalStateException tam je, cesta /home/proarc/.proarc/users/kortism/import/GD_973/proarc_import opravdu neexistuje. Otázka je, proč se na ní proarc stále snaží přistupovat.

Pak jsou tam ještě další chyby, ze kterých vůbec nejsem moudrý.

Jeden uživatel narazil na neočekávanou chyba při editování indexů stran, jinak o žádných problém z uživatelského pohledu nevím.

[logs.ZIP](https://github.com/proarc/proarc/files/1498971/logs.ZIP)

**Comment by jkremlacek** [comment]
```
Nov 20, 2017 2:52:24 PM cz.cas.lib.proarc.common.process.ExternalProcess run
WARNING: 1. failure, 
exit: -1,
out: , 
Cmd: [/home/proarc/kakadu/kdu_compress, -quiet, Cblk={64,64}, Corder=RPCL, Stiles={1024,1024}, Cprecincts={256,256},{256,256},{128,128}, ORGtparts=R, -rate, 0.8, Clayers=12, Clevels=5, Cmodes={BYPASS}, -no_palette, -i, /home/proarc/.proarc/users/janovak/import/L_666/L_666_117.tif, -o, /home/proarc/.proarc/users/janovak/import/L_666/proarc_import/L_666_117.NDK_USER.jp2]
```

z logu jde vyčíst, že chybu vyhodil kdu_compress (externí proces konverze tiff -> jp2), není zaplý verbose, takže těžko říct proč konverze padla.

Co mě napadá, tak na vině může např. být LZW komprese tiffu, kterou základní demo aplikace kakadu neumí zpracovat a musí být zkompilován s flag-em povolujícím LZW. 

Pokud o LZW nejde, tak spouštěcí příkaz z cmd je v segmentu logu výše, chybu by pomocí něj mělo jít zopakovat mimo ProArc, každopádně v tomto případě nejde o chybu ProArcu jako takového.

Selhávající tiff-y jsou:
/home/proarc/.proarc/users/kortism/import/U_2742/U_2742_203.tif
/home/proarc/.proarc/users/janovak/import/L_666/L_666_117.tif
/home/proarc/.proarc/users/kortism/import/GC_5257/GC_5257_002.tif


```
SEVERE: Servlet.service() for servlet [Jersey Web Application] in context with path [/proarc] threw exception [java.lang.IllegalStateException: Cannot resolve folder path: /home/proarc/.proarc/users/kortism/import/GD_973/proarc_import
```

Tady se zdá, že jde o poškozený importní balík, zkuste reimportovat celý adresář, zda se chyba bude opakovat.

**Comment by svetlym** [comment]
> přestalo to tedy dělat?

Těžko říct. Uživatel si ani před tím na nic nestěžoval. Obvykle se do logů koukám, jen když přijde uživatel s nějakým problémem, tentokrát jsem tam nahlížel, protože testujeme novou verzi. Že jde o jinou chybu jsem si nevšiml, neprohlížel jsem to tak důkladně. Budu to každopádně sledovat dál (už jsem o tom nejspíš zjistil víc, viz co píšu dál).

Ad kakadu: To je taky moje nepozornost, s chybami souvisejícími s Kakadu jsem se samozřejmě už několikrát setkal. Zajímavé je, že ty importy zjevně prošly. Kontroloval jsem teď titul L 666, v proarcu naimportovaný je a stránky se zobrazí. Zdrojový soubor (L_666_117.tif) je bez komprese. Nicméně tohle opravdu není problém proarcu.

Ad chyba s titulem GD_973: Už asi začínám tušit. V proarcu v historii importů jsem ho našel v kategorii "Načteno". Když na něj kliknu, tak to samozřejmě vyhodí chybu (javax.servlet.ServletException: java.lang.IllegalStateException: Cannot resolve folder path: /home/proarc/.proarc/users/kortism/import/GD_973/proarc_import for Batch{id=4909, folder=kortism/import/GD_973/...), protože adresář /home/proarc/.proarc/users/kortism/import/GD_973/ neexistuje.

Je možné, že uživatel smazal importní adresář dřív, než udělal to, čím se ukončuje import (tedy při čem se titul odstraní z historie importů)?

**Comment by jkremlacek** [comment]
Ad GD_973: ano, uživatel může importní adresář dostat do nekonzistentního stavu.

Pokud tedy v ProArc-u je daný adresář jako `Načteno`, tak nebyl uživatelem proveden krok uložení dávky po vybrání nadřazeného objektu ke skenům před smazáním importního adresáře. 

ProArc neřeší zamykání adresářů v době mezi importem skenů a uložením do fedory (kdy jsou veškerá data týkající se metadat apod. uložena v adresáři). Zásahy do adresáře v tomto časovém úseku tedy znamenají ve většině případů rozbití importní dávky.

**Comment by svetlym** [comment]
> ProArc neřeší zamykání adresářů v době mezi importem skenů a uložením do fedory

To asi ani není jak technicky udělat, leda těm souborům změnit přístupová práva na úrovni OS.

Asi by bylo hezké, kdyby to místo "neočekávaná chyba" napsalo něco jako "Smazal jste si importní adresář před tím, než jste přiřadil nadřazený objekt, import teď už nebude možné dokončit. Vytvořte znovu importní adresář se vstupními daty a pusťte import znovu", ale asi to přežijeme i bez toho ;-)

Každopádně děkuju za spolupráci s hledáním příčiny problému.

**Comment by svetlym** [comment]
Ještě mám k tématu jeden dotaz:

To, že někdo smazal importní adresář před přiřazením nadřazeného objektu, a tedy před importem do Fedory, se nám nestalo poprvé. Díky tomu v historii importů máme několik položek, které nejdou odstranit a kliknutí na ně vyhodí chybu a zapíše ji do logu. Je možné se jich nějak zbavit?

**Comment by jkremlacek** [comment]
UI momentálně neumožňuje smazání záznamu, který uživatel dostal do nekonzistentního stavu.

Záznam je možné smazat přímo v databázi proarcu:

1. v tabulce `proarc_batch` najít rozbitý záznam a získat jeho `id`
2. v tabulce `proarc_batch_item` smazat záznamy s daným `batch_id`
3. v tabulce `proarc_batch` smazat záznam s daným `id`
