### ISSUE TITLE
Ve verzi 3.4.3 nefunguje přidělení URN:NBN pro přílohu ročníku periodika.

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#744]
Když má periodikum čísla a přílohu k ročníku, tak číslům se URN:NBN přidělí, ale příloze ne - viz log:

```Apr 23, 2018 3:08:01 PM cz.cas.lib.proarc.common.urnnbn.UrnNbnService register
SEVERE: null
java.lang.IllegalStateException: uuid:cbdec887-31cb-481d-8261-2a2db662c96d: Cannot write URN:NBN urn:nbn:cz:abg001-00000j
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:530)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.processNdkPeriodicalIssue(UrnNbnVisitor.java:371)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:149)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visitNdkPeriodicalSupplement(UrnNbnVisitor.java:77)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:57)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:108)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:77)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.object.HierarchyObjectVisitor.visitChildren(HierarchyObjectVisitor.java:49)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visitNdkPeriodicalVolume(DefaultNdkVisitor.java:79)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:47)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:108)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:77)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.object.HierarchyObjectVisitor.visitChildren(HierarchyObjectVisitor.java:49)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visitNdkPeriodical(DefaultNdkVisitor.java:74)
	at cz.cas.lib.proarc.common.object.ndk.DefaultNdkVisitor.visit(DefaultNdkVisitor.java:49)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:108)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.visit(UrnNbnVisitor.java:77)
	at cz.cas.lib.proarc.common.object.DigitalObjectElement.accept(DigitalObjectElement.java:75)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnService.register(UrnNbnService.java:72)
	at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.registerUrnNbn(DigitalObjectResource.java:1398)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cz.cas.lib.proarc.common.fedora.DigitalObjectValidationException: PID: uuid:cbdec887-31cb-481d-8261-2a2db662c96d, dsId: BIBLIO_MODS, MODS validation
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkBeforeWrite(NdkMetadataHandler.java:451)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetadataHandler.java:537)
	at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadata(NdkMetadataHandler.java:138)
	at cz.cas.lib.proarc.common.urnnbn.UrnNbnVisitor.updateModsWithUrnNbn(UrnNbnVisitor.java:525)
	... 74 more
```

Zkoušeli jsme to nejdřív u existujícího periodika, pod kterým jsme vytvořili novou přílohu (tedy s novým uuid) a potom pro jistotu ještě u úplně nově vytvořeného periodika s nově vytvořenými čísly a přílohou. V obou případech nastala u přílohy stejná chyba.

Související problém je, že proarc následně povolí export (přestože příloha nemá urn:nbn) a čísla se sice vyexportují, ale příloha k ročníku ne (bez jakékoliv chybové hlášky ať už v browseru nebo v logu).

**Comment by SykoraLukas** [comment]
Popisovaný objekt nesplnuje všechny požadované pole podle standardu MODSu

**Comment by xRahman** [comment]
Děkuju za odpověď, už tápeme o něco míň. Dá se nějak zjistit, co přesně chybí?

**Comment by svetlym** [comment]
Děkuju za odpověď, už tápeme o něco míň. Dá se nějak zjistit, co přesně chybí?

**Comment by SykoraLukas** [comment]
Máte vyplněné vsechny povinné pole? Případně zkuste vyexportovat archivní balik a poslat mi ho mailem

**Comment by svetlym** [comment]
Ještě jednou jsme to zkontrolovali a jsou vyplněná stejná pole jako u jiných dokumentů, které chybu nedělají.

Vyexportovat archivní balík bohužel nepůjde - bez přiděleného URN:NBN (o čemž je právě tahle issue) nejde vyexportovat ani PSP. Archivní export vyplivne jen proarc_status.log a nic jiného.

**Comment by svetlym** [comment]
Tak nakonec je všechno jinak. Po konzultaci na gitteru jsme přišli na to, že to periodikum má stránky přímo pod ročníkem, nejsou tam žádná čísla. To způsobovalo jak problém s přidělováním URN:NBN, tak s exportem. Po vytvoření čísla obojí prošlo.

Tím je tenhle problém vyřešen - díky za konzultaci.
