### ISSUE TITLE
Nefungují exporty z ProArcu - CESJH, Crossref, K4 - ečlánky

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#775]
Informace o nefunkčních exportech jsem posílala už mailem (nejdřív 16. 5. a potom 1.6.), ještě zakládám issue. 

**CEJSH** – v exportu do CEJSHe se nezobrazují některá metadata – česká klíčová slova, český abstrakt, rozsah stran, u některých se číslo nezařadí do struktury časopisu.

V příloze mailu z 1.6. jsem posílala dva příklady těch exportů (těch blbých), jeden záznam je vytvořený v ProArcu a druhý je stažený z katalogu, je to poznat podle názvu, který je který.

 
**Crossref** – při exportu do Crossrefu ProArc hodí chybu:

Kompletní chybové hlášení:

```
[ERROR: Missing cejsh_journals parameter: depositor_name or email_address, for ISSN: 0032-7786; SystemID: jar:file:/home/proarc/apache-tomcat8/webapps/proarc/WEB-INF/lib/proarc-common-3.4.1.jar!/cz/cas/lib/proarc/common/export/crossref/mods_crossref.xsl; Line#: 78; Column#: 42]
cz.cas.lib.proarc.common.export.ExportException: Transformation errors!
    at cz.cas.lib.proarc.common.export.crossref.CrossrefBuilder.createPackage(CrossrefBuilder.java:152)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportPackage(CrossrefExport.java:107)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportImpl(CrossrefExport.java:77)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.export(CrossrefExport.java:48)
    at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newCrossrefExport(ExportResource.java:315)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
    at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
    at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
```
 

Něco se vyexportuje, ale je to prázdný.

 

No, a **K4 export** u čísla časopisu taky nějak blbne. Z ProArcu exportujeme někdy po celých ročnících, ale většinou po číslech.

Export čísla:
Exporty - Export pro Kramerius 4
Pak to číslo naimportuju do Krameria a normálně se zařadí do té struktury: titul periodika – ročník – číslo.

Ale u některých čísel (třeba Český časopis historický – export posílám v příloze) se to číslo v Krameriovi vůbec nezobrazí, ani ve struktuře v záznamu časopisu, a ani ve výsledcích vyhledávání.  Pak jsme zkoušely do Krameria naimportovat úplně celý časopis z ProArcu, ptž jsme myslely, že tam třeba někde chybí ta struktura. A nejen, že se v tom časopisu nezobrazilo to požadované číslo 1/2018, ale ještě k tomu to vyhodilo další dvě čísla (z ročníku 2012) úplně mimo a je možné je najít jen přes vyhledávání.

Odkaz na časopis do testovacího Krameria: https://k4test.lib.cas.cz/search/handle/uuid:9da3b368-45b9-11e1-a671-005056a60003

 

Další možnost je, že se číslo zařadí do struktury časopisu, ale když ho chci rozbalit, tak tam nic není. Jde najít přes výsledky vyhledávání (příklad Knihy a dějiny):
![knihydejiny](https://user-images.githubusercontent.com/21309201/42036519-05a52da0-7ae6-11e8-9239-1a6e6080782e.jpg)

 
![knihydejiny2](https://user-images.githubusercontent.com/21309201/42036537-136317fe-7ae6-11e8-8e1b-3e602b687708.jpg)

Další možnost je, že to číslo najdu jen přes výsledky vyhledávání, ale ve struktuře se vůbec neobjeví (například rok 1997 na screenshotu výše, kde je struktura toho časopisu vůbec není, ale přes vyhledávání jsem ho našla).

Odkaz do testovacího Krameria: https://k4test.lib.cas.cz/search/i.jsp?pid=uuid:fc144bf1-8d61-4f4b-80f9-e4a772db32dc&q=knihy%20a%20d%C4%9Bjiny

U těch čísel, která jsou vyhozená mimo, se mi stává, že když ho přes výsledky vyhledávání najdu a otevřu, tak tam nic není (jen obálka):
![nezobrazisekad](https://user-images.githubusercontent.com/21309201/42036552-1eb4409c-7ae6-11e8-8a93-20d1ae0e6dac.jpg)

**Comment by melichova** [comment]
Prosím o co nejrychlejší vyřešení. Tento problém je znám cca od půlky dubna a nic se neděje... Potřebujeme data z ProArcu posílat do jiných databází. Díky.

**Comment by krizovj** [comment]
Zkoušeli, ale nepomohlo to. Jednou jsme taky zkusili celý časopis smazat a znovu ho vyexportovat z ProArcu a naimportovat do Krameria (nebyl to moc velký časopis, tak jsme to zkusili). No a to nám udělalo dokonce to, že to vyhodilo mimo tu strukturu některá už dříve nahraná čísla, která předtím byla v Krameriovi zařazena správně... Ale asi jak se znovu udělal ten export, tak se to prostě udělalo špatně.

**Comment by MartinRumanek** [comment]
Je to několik různých problémů, zatím se mi podařilo zreplikovat pouze Crossref - vyčlenil jsem ho do zvláštního issue https://github.com/proarc/proarc/issues/777

Cejsh se mi zatím nasimulovat nepodařil - asi budu potřebovat návod jak udělat data, která spadnou do chyby.

**Comment by MartinRumanek** [comment]
@krizovj Nedaří se mi dohledat K4 export časopisu "Český časopis historický", můžeš mi to prosím poslat znovu?

Možnost si prohlídnout poškozené periodikum přímo v Krameriu by se mi hodila, ale na https://k4test.lib.cas.cz/ se nedostanu. Bylo by to možné povolit na IP adresu? (@mduda100871).

**Comment by krizovj** [comment]
Poslala jsem ti přes FileSender ten export časopisu Český časopis historický číslo 2018/1.

**Comment by tumovam** [comment]
Problém s "vyhazováním" čísel (resp. špatným zařazením čísel do struktury titul periodika – ročník – číslo), která obsahují články v PDF, stále přetrvává. 
Tentokrát jsem vyexportovala celý ročník 2018 (čas. Český časopis historický, uuid:0b1606d3-a580-4dde-ba08-3a6509caa9b7) a opět se mi jednotlivá čísla "vyházela" mimo periodkum: 
![obrazek](https://user-images.githubusercontent.com/31240271/51384335-52945d80-1b1c-11e9-816e-9dd0d14720a3.png)

Navíc číslo vypadá, jako by v Krameriovi bylo, ale po rozkliknutí se zobrazí hláška "Data není možné zobrazit, můžete si stáhnout originální data. Originál". Pokud kliknu na "Originál", otevře se čtečka PDF s plným textem obálky daného čísla. 
![obrazek](https://user-images.githubusercontent.com/31240271/51384361-650e9700-1b1c-11e9-8ca4-cd220b4b8394.png)

V rels-ext vazbách jsou čísla správně zařazená v ročníku. 
Nepomohla ani reindexace čísel, stále je vidět pouze obálka. 
Indexace podle PID selhává, i přes to, že jednotlivé články v Krameriovi podle PID najdu. 

Asi to nesouvisí s exportem pro CESJH a Crossref, mám tedy založit nové issue? 
Může být chyba na straně Krameria? 
Děkuju!

**Comment by SykoraLukas** [comment]
CEJSCH funguje od [verze 3.5.7](https://github.com/proarc/proarc/releases/tag/v3.5.7)

**Comment by SykoraLukas** [comment]
CROSSREF funguje od [verze 3.5.8](https://github.com/proarc/proarc/releases/tag/v3.5.8)

**Comment by SykoraLukas** [comment]
Po vyjádření @krizovj  issue zavírám
