### ISSUE TITLE
Nefunkční Crossref pro nedefinované ISSN

### ISSUE THREAD

**Issue by MartinRumanek** [proarc/proarc#777]
**Crossref** – při exportu do Crossrefu ProArc hodí chybu:

Kompletní chybové hlášení:

```
[ERROR: Missing cejsh_journals parameter: depositor_name or email_address, for ISSN: 0032-7786; SystemID: jar:file:/home/proarc/apache-tomcat8/webapps/proarc/WEB-INF/lib/proarc-common-3.4.1.jar!/cz/cas/lib/proarc/common/export/crossref/mods_crossref.xsl; Line#: 78; Column#: 42]
cz.cas.lib.proarc.common.export.ExportException: Transformation errors!
    at cz.cas.lib.proarc.common.export.crossref.CrossrefBuilder.createPackage(CrossrefBuilder.java:152)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportPackage(CrossrefExport.java:107)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportImpl(CrossrefExport.java:77)
    at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.export(CrossrefExport.java:48)
    at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newCrossrefExport(ExportResource.java:315)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
    at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
    at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
```
 

Něco se vyexportuje, ale je to prázdný.

Problém nahlášený @krizovj

**Comment by MartinRumanek** [comment]
Ta chybová hláška je nesrozumitelná, ale chyba je v tom, že pro Crossref export jsou definované některé údaje přímo ve zdrojových kódech proarcu. Konkrétně se jedná o tento soubor https://github.com/proarc/proarc/blob/master/proarc-common/src/main/resources/cz/cas/lib/proarc/common/export/cejsh/cejsh_journals.xml.

Musíme teda doplnit issn, které v KNAV potřebujete. Kolik jich je? Uživatelsky to teď bohužel měnit nejde.

**Comment by melichova** [comment]
Momentálně se jedná o 2 časopisy:
Knihy a dějiny ISSN 1210-8510
Preslia ISSN 0032-7786

**Comment by MartinRumanek** [comment]
No, ale musíme vyplnit jednotlivé hodnoty https://github.com/proarc/proarc/blob/master/proarc-common/src/main/resources/cz/cas/lib/proarc/common/export/cejsh/cejsh_journals.xml#L4-L15

Nejsem si jistý jakým způsobem se přiděluji ta ID journalId a publisherId...

Pro "Knihy a dějiny" je to publisherId AV http://cejsh.icm.edu.pl/cejsh/element/bwmeta1.element.18ec9101-da63-3687-b222-87ff0f2b4978, ale pro Preslii nevím - Česká Botanická společnost v Cejshi není. A stejně potřebuji ještě jourelId pro oba časopisy.

Nejspíš je to náhodně vygenerovaný uuid identifikátor - ale bylo by dobré to ověřit, nevíte prosím u koho?

**Comment by melichova** [comment]
Nemohlo dojít k záměně šablony pro jednotlivé exporty do CEJS a Crossref. Pokud tedy mají odlišnou šablonu, což by asi měly mít...? Když chci udělat export do Crossref, tak vyskočí zmiňovaná chybová hláška, kde je však zmiňovaný CEJSH... Zrovna preslia se do Cejshe neposílá, pouze do Crossrefu. A právě proto, že tam není povolené ISSN pro Preslii, ten export neproběhne a vyhodí to chybu...

**Comment by MartinRumanek** [comment]
Ona totiž crossref šablona používá některé hodnoty z nastavení Cejshe, ale vypadá to, že depositorName a emailAddress bude stačit. Ta ID můžu nechat pro Crossref prázdná. Vyzkouším to.

**Comment by melichova** [comment]
Zjišťuji, zda nedošlo k záměně u nás při přechodu na novou verzi a následné vracení na starou, které jsme řešili v dubnu. Protože teď mi došlo, že ten export, který je funkční do CEJSHe zobrazuje jenom to, co je požadováno do Crossrefu, tím se vysvětlují chybějící česká klíčová slova, abstrakty a stránky. A logicky export CEJSH neprojde přes šablonu Crossrefu.

**Comment by melichova** [comment]
Výměna šablon se nepotvrdila. Testovala jsem export do Crossref na na obou časopisech. 
Časopis Preslia exportujeme pouze do Crossref a export vůbec neproběhne a vyhodí výše uvedenou chybu.
Časopis Knihy a dějiny exportujeme do Crossref a CEJSH a tam oba exporty proběhnou bez problému.
Vytvoření záznamů v konkrétní verzi v tomto případě nemá vliv. 
Nemůže v tomto případě být problém v tom, že ProArc "nenacita nase sablony, ale sve defaultni"? (Knihy a dějiny byly pravděpodobně řešeny pro tento export jako první a Preslie se přidávala až později).

**Comment by MartinRumanek** [comment]
> Nemůže v tomto případě být problém v tom, že ProArc "nenacita nase sablony, ale sve defaultni"? (Knihy a dějiny byly pravděpodobně řešeny pro tento export jako první a Preslie se přidávala až později).

Vy máte vlastní šablony? Potom je blbost abych to zkoušel bez nich... Můžete je přiložit k issue/zaslat mi je mailem?

**Comment by SykoraLukas** [comment]
@krizovj ke zprovoznění Crossrefu potřebuji pro jednotlivé periodika ISSN, depositorName a emailAdress jako je vyplněno v [šabloně pro export Crossref](https://github.com/proarc/proarc/blob/bdf52bfa4cd86ebda82bf0cec5614448220af594/proarc-common/src/main/resources/cz/cas/lib/proarc/common/export/cejsh/cejsh_journals.xml#L268-L281)

**Comment by krizovj** [comment]
Poslala jsem ti ty údaje na mail.

**Comment by krizovj** [comment]
Je potřeba něco upravovat v konfiguraci, aby to fungovalo? 

Teď už se to sice vyexportuje, ale v tom exportu jsou jen údaje o časopisu, chybějí údaje k článkům. 

Tady:
![blbe](https://user-images.githubusercontent.com/21309201/56724343-1ab83a00-674b-11e9-85e3-bc469e6e338b.jpg)

Má toho tam být mnohem víc (do printscreenu se mi nevešel celý záznam, takže ho klidně pošlu, pokud to bude potřeba):
![spravne](https://user-images.githubusercontent.com/21309201/56724475-610d9900-674b-11e9-97fc-2dfbde4daebf.jpg)

**Comment by krizovj** [comment]
Zdá se, že už to funguje!
