### ISSUE TITLE
Test v5.3.4 - chyba STT NDK export

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#894]
Po pokusu (celkem 3 různé tituly) udělat NDK balíček z STT se mi objevila tato chyba:

![obrazek](https://user-images.githubusercontent.com/13831946/52626118-cecb5800-2eb2-11e9-8e63-6e6112286725.png)

**Comment by SykoraLukas** [comment]
Mohl bych poprosit o více informací k této chybě? Z jakého modelu se exportuje, jak vypadá hierarchický strom daného modelu, jaká data (metadata, ocr, alto, user.jp2, master.jp2) jsou pro jednotlivé strany vyplněny?

**Comment by nezbedova** [comment]
Jedná se o NDK pro STT, takže exportuji za stávajícího modelu STT Svazek monografie.
Vyplněna jsou metadata na stranu. Jak vypadá  hierarchický strom daného modelu netuším. Rozhodně tam není ocr a alto. Pokud to jde jen na nově naimportovaných STT, které budou mít OCR, které bude prázdné, tak nevím, jak z ProArcu dostaneme NDK balíčky pro STT, které tam jsou.

**Comment by nezbedova** [comment]
Po nahrání a zpracování nového STT, který u sebe měl xml a txt (jako mívá NDK monografie) se objevila tato hláška:
![obrazek](https://user-images.githubusercontent.com/13831946/52930642-76c8a180-3349-11e9-891c-3d66275a2500.png)

**Comment by SykoraLukas** [comment]
Bylo by možné vyexportovat celou chybovou hlášku? Děkuji

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/52946569-9aeda800-3374-11e9-841e-75c3de885fbb.png)
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<exports xmlns="http://proarc.lib.cas.cz/xml/common/export/v1/">
    <export>
        <begin>2019-02-18T11:57:29.767+01:00</begin>
        <end>2019-02-18T11:57:35.265+01:00</end>
        <status>FAILED</status>
        <inputPid>uuid:8cd1ba41-00cf-422b-8e49-66d825b7136a</inputPid>
        <error message="Unable to save mets file:/media/vg1-lv1/proarc-test/work_data/users/nezbedova/export/8cd1ba41-00cf-422b-8e49-66d825b7136a_2/8cd1ba41-00cf-422b-8e49-66d825b7136a/mets_8cd1ba41-00cf-422b-8e49-66d825b7136a.xml" pid="uuid:8cd1ba41-00cf-422b-8e49-66d825b7136a">cz.cas.lib.proarc.common.export.mets.MetsExportException: Invalid info file:/media/vg1-lv1/proarc-test/work_data/users/nezbedova/export/8cd1ba41-00cf-422b-8e49-66d825b7136a_2/8cd1ba41-00cf-422b-8e49-66d825b7136a/info_8cd1ba41-00cf-422b-8e49-66d825b7136a.xml
	at cz.cas.lib.proarc.common.export.mets.MetsUtils.saveInfoFile(MetsUtils.java:824)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElementVisitor.saveMets(MetsElementVisitor.java:325)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElementVisitor.insertIntoMets(MetsElementVisitor.java:1968)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElement.accept(MetsElement.java:531)
	at cz.cas.lib.proarc.common.export.mets.NdkExport.export(NdkExport.java:137)
	at cz.cas.lib.proarc.common.export.mets.NdkExport.export(NdkExport.java:84)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newNdkExport(ExportResource.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
</error>
    </export>
</exports>

**Comment by nezbedova** [comment]
Hláška z okna:
cz.cas.lib.proarc.common.export.mets.MetsExportException: Invalid info file:/media/vg1-lv1/proarc-test/work_data/users/nezbedova/export/8cd1ba41-00cf-422b-8e49-66d825b7136a_2/8cd1ba41-00cf-422b-8e49-66d825b7136a/info_8cd1ba41-00cf-422b-8e49-66d825b7136a.xml
	at cz.cas.lib.proarc.common.export.mets.MetsUtils.saveInfoFile(MetsUtils.java:824)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElementVisitor.saveMets(MetsElementVisitor.java:325)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElementVisitor.insertIntoMets(MetsElementVisitor.java:1968)
	at cz.cas.lib.proarc.common.export.mets.structure.MetsElement.accept(MetsElement.java:531)
	at cz.cas.lib.proarc.common.export.mets.NdkExport.export(NdkExport.java:137)
	at cz.cas.lib.proarc.common.export.mets.NdkExport.export(NdkExport.java:84)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newNdkExport(ExportResource.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nezbedova** [comment]
Nefunguje ani u v.3.5.5

**Comment by SykoraLukas** [comment]
Mohl bych vás poprosit o zaslání balíčku, který se vyexportuje? Potřebuji zjistit, proč se nepodaří validovat INFO file

**Comment by nezbedova** [comment]
Hláška se objevuje. Balíček posílám.

**Comment by SykoraLukas** [comment]
Opraveno
