### ISSUE TITLE
STT export Archive

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#926]
Podle #624 byl vytvořen NDK balíček pro STT 
Je třeba ještě exportovat Archive balíček pro STT, který bude obsahovat stejné položky jako Archive balíček pro NDK monografie.

**Comment by krizovj** [comment]
19. 5. 2020: STT se nebude přidělovat urn:nbn

**Comment by tumovam** [comment]
Ve verzi 3.6.4-preview export acrhive balíčku pro STT funguje. Ještě budu chvilku zkoumat a testovat. Ale na první pohled dobrý ;) Díky! M.

**Comment by tumovam** [comment]
Nový archive balíček pro STT obsahuje tyto složky:

AUDIT
DESCRIPTION
FOXML
FULL
NDK - ve složce je kompletní NDK balíček obsahující složky: amdsec, mastercopy, usercopy, chybí alto a txt, protože ty nejsou pro STT povinné, a dále obsahuje info, md5 a mets
PREVIEW
RAW
RAW_MIX
RELS_EXT
THUMBNAIL
mets
(Original_Tif_LZW + md5), které zatím v KNAV přidáváme ručně

Všechny soubory obsažené ve složkách mají prefix tzn. audit_, description_, foxml_, full_, preview_, raw_, raw_mix_, rels-ext_, thumbnail_

**Comment by tumovam** [comment]
Jen pro přehled - export STT nefunguje ve v3.6.4.

**Comment by tumovam** [comment]
Export STT ve v3.6.5 funguje. Mets už se nejmenuje main_mets 👍

**Comment by tumovam** [comment]
Archivace Starých tisků ve v3.6.6 vypadá ok.

**Comment by nezbedova** [comment]
Archive lze udělat ze stávajících záznamů.

Pokud založím nový STT přes Nový objekt nebo přes záměr, tak mi to při archivaci hodí chybu:

DigitalObjectElement{item=model:oldprintvolume, uuid:b413b8a3-3548-4bcc-93b2-0e4bbbd1e0c2, Spicilegium didacticum, handler=cz.cas.lib.proarc.common.object.DigitalObjectHandler@3887295}
java.lang.NullPointerException
	at cz.cas.lib.proarc.common.export.archive.PackageBuilder.addStreamAsFile(PackageBuilder.java:299)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processDevice(ArchiveObjectProcessor.java:213)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processDatastreams(ArchiveObjectProcessor.java:153)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:117)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processChildren(ArchiveObjectProcessor.java:237)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.processObject(ArchiveObjectProcessor.java:123)
	at cz.cas.lib.proarc.common.export.archive.ArchiveObjectProcessor.process(ArchiveObjectProcessor.java:101)
	at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archiveImpl(ArchiveProducer.java:84)
	at cz.cas.lib.proarc.common.export.archive.ArchiveProducer.archive(ArchiveProducer.java:69)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newArchive(ExportResource.java:561)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:525)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1621)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SykoraLukas** [comment]
Prosím o kontrolu, zda mají strany přiděleno Digitalizační zařízení. Podle logu to vypadá, že nemají. Nyní jsem vytvořil na testu STT monografii "D Test", naimportoval k ní nové strany a dal exportovat a vše proběhlo v pořádku.

**Comment by nezbedova** [comment]
Opravdu tam není zařízení. Nenapadlo mě to zjišťovat, protože bez vybraného Zařízení nelze skeny načíst.
 Vybrala jsem zařízení pojmenované jako Nezjištěno - replikace. Zařízení se vybírá na jednotlivé strany. Titul ho nemá vyplněný.

**Comment by SykoraLukas** [comment]
Titul ho ani vyplněný mít nemá, musí to mít jen strany. Ve starém klientovi to načíst bez zařízení nelze, v novém netuším. Ale nejspíš to půjde, což je nejspíš ten důvod, jak k tomu došlo.

**Comment by nezbedova** [comment]
Dělala jsem to ve starém PA, v.3.6.7. 
Načíst bez zařízení nelze.

**Comment by SykoraLukas** [comment]
Tak tím pádem netuším, jak to, že jsou strany bez digitalizačního zařízení.

**Comment by nezbedova** [comment]
@SykoraLukas Už vím, v čem je problém. 

Pokud u zařízení nejsou vyplněná povinná pole, tak to hodí tu chybu.

U Zařízení Zeutschel projde
![obrazek](https://user-images.githubusercontent.com/13831946/122925663-579e0c80-d367-11eb-8808-ee94552ec1d1.png)

U Zařízení Nezjištěno - replikace neprojde:

![obrazek](https://user-images.githubusercontent.com/13831946/122925774-73091780-d367-11eb-9f56-bd17e7dc160c.png)

**Comment by SykoraLukas** [comment]
Super, takže toto je vyřešeno? Dá se tedy model vyexportovat?

**Comment by nezbedova** [comment]
Ověřeno na novém zařízení. 

Je to vyřešené. Exporty archive pro STT jdou. Chyba uvedená výše se váže k nevyplněným údajům zařízení..

**Comment by SykoraLukas** [comment]
Děkuji, vracím tedy label Release 3.6.4. a k testování.

**Comment by nezbedova** [comment]
Archive balíček pro STT z v. 3.7 kontroloval @kerschfilip 

Připravím mu ke kontrole další. Z v 3.7.1

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, balíčky z 3.7.1 prošly kontrolou v rámci ostrého provozu - není to tedy k uzavření? Děkuji.

**Comment by nezbedova** [comment]
Hotovo. Zavírám.
