### ISSUE TITLE
[DOTAZ] Potíže s importem audio dokumentů

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#946]
Dobrý den,

zkouším importovat zvukové dokumenty a nedaří se. Import proběhne, ale jsou pak vidět jen obrazové soubory, žádné zvukové.

Jako nejpravděpodobnější příčina mi přijde tohle:

```
WARNING: Model ID duplicates! model:ndkmonographsupplement, ndk overrides ndkAudio plugin.
May 03, 2019 12:25:00 PM cz.cas.lib.proarc.common.object.model.MetaModelRepository registerModels
WARNING: Model ID duplicates! model:page, ndk overrides ndkAudio plugin.
```

Nastavení pluginů v configuračním souboru mám následující:

```
digobject.plugins=ndk, oldprint, bdm, ndkAudio
```

Nemám představu, jak to vyřešit.

**Comment by svetlym** [comment]
Doplňující informace (kdyby byla chyba v něčem jiném, než si myslím):

Použitý konfigurační soubor (pro účely testování importu zvukových dokumentů jsem zatím disabloval importní profil a snažím se to zprovoznit v defaultním. Importuju také rovnou jp2, neprovádí se tedy konverze z tiffu při importu):
```
#
# ProArc Configuration Template
#
# Version 1.0
#
# The template lists default properties. To override them copy given properties
# to $PROARC_HOME/proarc.cfg.
#
# The template file is auto generated and all changes will be descarded!

## Default location for user data. It contains newly created user home folders.
proarc.users.home=${proarc.home}/users

## Fedora client credentials
fedora.client.url=http://localhost:8080/fedora
fedora.client.username=fedoraAdmin
fedora.client.password=*****

## Bibliographic metadata catalogs
#catalogs=oai,aleph_nkp,rdcz,z3950
catalogs=oai,aleph_nkp,rdcz

# OAI
# (2.1) povinné URL OAI serveru
catalog.oai.url=http://web2.mlp.cz/cgi/oai
# (2.1) povinné označení katalogu
catalog.oai.type=OAICatalog
# (2.1) název katalogu zobrazený uživateli
catalog.oai.name=Koniáš
# (2.1) povinný OAI metadata prefix pro data ve formátu http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd
catalog.oai.metadataPrefix=marc21
# (2.1) nepovinný prefix identifikátoru, který se přidá před hodnotu vyplněnou uživatelem
catalog.oai.identifierPrefix=oai:www.mlp.cz:
# (2.1) povolená pole: id
catalog.oai.fields=id
# (2.1) název pole zobrazený uživateli
catalog.oai.field.id.title=Identifikátor

# RD CZ
catalog.rdcz.url=http://registrdigitalizace.cz/soapservices
catalog.rdcz.name=registrdigitalizace.cz
catalog.rdcz.user=vojirova
catalog.rdcz.password=*****
catalog.rdcz.type=DigitizationRegistryCatalog
# (2.0) fields - seznam všech možných polí: barcode, ccnb, isbn, issn, signature, title
catalog.rdcz.fields=isbn
# (2.0) title - změna názvu pole v UI
catalog.rdcz.field.isbn.title=ISBN

# Aleph NKP
catalog.aleph_nkp.url=http://aleph.nkp.cz/X?base=nkc
catalog.aleph_nkp.name=Aleph NKP
catalog.aleph_nkp.type=AlephXServer

# Z39.50
# <port> is mandatory!
#catalog.z3950.url=<hostname>:<port>
#catalog.z3950.base=DATABASE_ID
#catalog.z3950.name=Z39.50 Catalog
#catalog.z3950.type=Z3950Catalog
# recordCharset is optional; use in case the server returns records with unexpected charset
# http://docs.oracle.com/javase/6/docs/api/java/nio/charset/Charset.html
#catalog.z3950.recordCharset=UTF-8
## optional fields declaration
## query - field property to redefine RPN query. %s is replaced with query terms
##         see http://www.indexdata.com/zebra/doc/querymodel-rpn.html
#catalog.z3950.fields=issn, isbn
#catalog.z3950.field.issn.query=@attrset bib-1 @attr 1=8 "%s"
#catalog.z3950.field.isbn.query=@attrset bib-1 @attr 1=7 "%s"


## Import options

# Algorithm to scale an image with java.image.
# Supported values:
#   AREA_AVERAGING, BICUBIC_STEPPED, BILINEAR, BICUBIC, BILINEAR_STEPPED,
#   NEAREST_NEIGHBOR, NEAREST_NEIGHBOR_STEPPED, REPLICATE
import.image.java.scalingMethod=BICUBIC_STEPPED

## PREVIEW datastream
# max width to scale origin scan
#import.image.preview.maxWidth=
# max height to scale origin scan
import.image.preview.maxHeight=1000
# Algorithm to scale an image.
import.image.preview.java.scalingMethod=${import.image.java.scalingMethod}

## THUMBNAIL datastream
# max width to scale origin scan
import.image.thumbnail.maxWidth=120
# max height to scale origin scan
import.image.thumbnail.maxHeight=128
# Algorithm to scale an image.
import.image.thumbnail.java.scalingMethod=${import.image.java.scalingMethod}

## TEXT_OCR datastream
# The filename suffix to match file containing plain text OCR.
# In case of ABA00726009905207199800001.tif scan the import will look
# for related ABA00726009905207199800001.ocr.txt.
import.text_ocr.file.suffix=.ocr.txt
# The encoding of plain text OCR
import.text_ocr.file.charset=UTF-8

# required input files
#default for NDK: import.requiredDatastreamId=ALTO, NDK_ARCHIVAL, NDK_USER, TEXT_OCR
##import.requiredDatastreamId=ALTO, NDK_ARCHIVAL, NDK_USER, TEXT_OCR
import.requiredDatastreamId=NDK_ARCHIVAL, NDK_USER, NDK_AUDIO_ARCHIVAL, NDK_AUDIO_USER, TEXT_OCR, ALTO

## Test of import of audio documents
import.ndk_audio_archival.file.suffix=.mc.wav
import.ndk_audio_user.file.suffix=.uc.mp3
import.ndk_archival.file.suffix=.mc.jp2
import.ndk_user.file.suffix=.uc.jp2
import.alto.file.suffix=.xml
import.text_ocr.file.suffix=.txt


## Kramerius4 export options

# list datastreams to exclude from export
export.kramerius4.excludeDatastreamId=AUDIT, RAW, PRIVATE_NOTE

# export.kramerius4.rename.<datastreamId>=krameriusDatastreamId
# mapping of ProArc datastream IDs to Kramerius IDs
export.kramerius4.rename.FULL=IMG_FULL
export.kramerius4.rename.PREVIEW=IMG_PREVIEW
export.kramerius4.rename.THUMBNAIL=IMG_THUMB

# default access policy used for exported object. Values: policy:private|policy:public|<empty>
export.kramerius4.policy=policy:private

# (2.0) Čárkou oddělený seznam profilů. Zatím se využívá jen první.
urnnbn.resolvers=mlp-test

## Testovací resolver
# (2.0) ID registrátora
urnnbn.resolver.mlp-test.registrar=abg001
# (2.0) Uživatelský popis profilu.
urnnbn.resolver.mlp-test.title=MLP Test
# (2.0) URL kde běží služba resolveru.
urnnbn.resolver.mlp-test.url=https://resolver-test.nkp.cz/api/v3
# (2.0) Uživatelské jméno pro přihlášení k resolveru.
urnnbn.resolver.mlp-test.user=Mestska_knihovna
# (2.0) Heslo pro přihlášení k resolveru.
urnnbn.resolver.mlp-test.passwd=1hewHe

## Ostrý resolver
# (2.0) ID registrátora
urnnbn.resolver.mlp.registrar=abg001
# (2.0) Uživatelský popis profilu.
urnnbn.resolver.mlp.title=MLP
# (2.0) URL kde běží služba resolveru.
urnnbn.resolver.mlp.url=https://resolver.nkp.cz/api/v3
# (2.0) Uživatelské jméno pro přihlášení k resolveru.
urnnbn.resolver.mlp.user=MLP_digitalizace
# (2.0) Heslo pro přihlášení k resolveru.
urnnbn.resolver.mlp.passwd=ezNka2Hqd




## Nastavení kakadu (konverze tiffu do jp2):
# (2.0) ID profilu externího procesu pro vytvoření archivní kopie.
import.ndk_archival.processor=kdu_ac
# (2.0) ID profilu externího procesu pro vytvoření uživatelské kopie.
import.ndk_user.processor=kdu_uc

# cesty k externi aplikaci kakadu
KDU_HOME=/home/proarc/kakadu
KDU_EXEC=${KDU_HOME}/kdu_compress
KDU_LIBPATH=${KDU_HOME}

## Nastavení pro archivní kopii dle NDK.
# (2.0) Plná cesta spustitelného externího procesu.
processor.kdu_ac.exec=${KDU_EXEC}
# (2.0) Plná cesta k adresáři s knihovnami kdu. Nepovinné, pokud jsou knihovny dostupné pro tomcat.
processor.kdu_ac.environment.LD_LIBRARY_PATH=${KDU_LIBPATH}
# (2.0) Typ procesu.
processor.kdu_ac.type=kdu_compress
# (2.0) Parametry externího procesu.
processor.kdu_ac.arg=-quiet
processor.kdu_ac.arg=Cblk\={64\,64}
processor.kdu_ac.arg=Corder\=RPCL
processor.kdu_ac.arg=Stiles\={4096\,4096}
processor.kdu_ac.arg=Cprecincts\={256\,256}\,{256\,256}\,{128\,128}
processor.kdu_ac.arg=ORGtparts\=R
processor.kdu_ac.arg=Creversible\=yes
processor.kdu_ac.arg=Clayers\=1
processor.kdu_ac.arg=Clevels\=5
processor.kdu_ac.arg=Cmodes\={BYPASS}
processor.kdu_ac.arg=Cuse_sop\=yes
processor.kdu_ac.arg=Cuse_eph\=yes
processor.kdu_ac.arg=-double_buffering
processor.kdu_ac.arg=32
processor.kdu_ac.arg=-no_palette
# (2.0) Maximální očekávaná doba běhu procesu v ms; 0 - znamená že se čeká věčně; standardně se čeká 2 min.
processor.kdu_ac.timeout=120000
# (2.0) počet pokusů opětovného spuštění procesu, pokud skončil neočekávaně; standardně 0
processor.kdu_ac.retry=1

## Nastavení pro uživatelskou kopii dle NDK.
# (2.0) Plná cesta spustitelného externího procesu.
processor.kdu_uc.exec=${KDU_EXEC}
# (2.0) Plná cesta k adresáři s knihovnami kdu. Nepovinné, pokud jsou knihovny dostupné pro tomcat.
processor.kdu_uc.environment.LD_LIBRARY_PATH=${KDU_LIBPATH}
# (2.0) Typ procesu.
processor.kdu_uc.type=kdu_compress
# (2.0) Parametry externího procesu.
processor.kdu_uc.arg=-quiet
processor.kdu_uc.arg=Cblk\={64\,64}
processor.kdu_uc.arg=Corder\=RPCL
processor.kdu_uc.arg=Stiles\={1024\,1024}
processor.kdu_uc.arg=Cprecincts\={256\,256}\,{256\,256}\,{128\,128}
processor.kdu_uc.arg=ORGtparts\=R
processor.kdu_uc.arg=-rate
processor.kdu_uc.arg=0.8
#processor.kdu_uc.arg=Creversible\=no
processor.kdu_uc.arg=Clayers\=12
processor.kdu_uc.arg=Clevels\=5
processor.kdu_uc.arg=Cmodes\={BYPASS}
processor.kdu_uc.arg=-no_palette
# (2.0) Maximální očekávaná doba běhu procesu v ms; 0 - znamená že se čeká věčně; standardně se čeká 2 min.
processor.kdu_uc.timeout=120000
# (2.0) počet pokusů opětovného spuštění procesu, pokud skončil neočekávaně; standardně 0
processor.kdu_uc.retry=1

# seznam aktivních ID pluginů
## Tohle není třeba uvádět, použijou se pak automaticky všechny pluginy.
## Je to tu proto, aby se nepoužil outdated k4 plugin, který obsahuje konfliktní
#digobject.plugins=ndk, oldprint, bdm
digobject.plugins=ndk, oldprint, bdm, ndkAudio

# Importní profily
#import.profiles=profile.default, profile.soundrecording_import

#profile.soundrecording_import.label=Zvukové dokumenty
#profile.soundrecording_import.description=Profil pro import zvukových dokumentů.
#profile.soundrecording_import.file=proarc.soundrecording.cfg
```

V importním adresáři je celkem 14 souborů. Proarc ale při importu hlásí, že jich importuje 8:

```
CO-248539433021-01-0001.mc.jp2
CO-248539433021-01-0001.ocr.txt
CO-248539433021-01-0001.ocr.xml
CO-248539433021-01-0001.uc.jp2
CO-248539433021-01-0002.mc.jp2
CO-248539433021-01-0002.ocr.txt
CO-248539433021-01-0002.ocr.xml
CO-248539433021-01-0002.uc.jp2
MC-248539433021-01-01-00.mc.wav
MC-248539433021-01-02-00.mc.wav
U1-248539433021-01-01-01.uc.mp3
U1-248539433021-01-01-02.uc.mp3
U1-248539433021-01-02-01.uc.mp3
U1-248539433021-01-02-02.uc.mp3
```

Kromě zmíněného warningu jsou pak v logu ještě následující:

```
WARNING:   No rules found matching 'Context/Resources/PreResources'.
May 03, 2019 12:24:50 PM org.apache.tomcat.util.digester.Digester endElement
WARNING:   No rules found matching 'Context/Resources/PreResources'.
May 03, 2019 12:24:50 PM org.apache.tomcat.util.digester.Digester endElement
WARNING:   No rules found matching 'Context/Resources/PostResources'.
```

**Comment by svetlym** [comment]
Zkusil jsem to samé ve verzi 3.5.9 a problém přetrvává:

```
May 24, 2019 1:38:59 PM cz.cas.lib.proarc.common.object.model.MetaModelRepositor
y registerModels
WARNING: Model ID duplicates! model:ndkmonographsupplement, ndk overrides ndkAud
io plugin.
```

Pokusu o import pak vyhodí výjimku:

```
May 24, 2019 4:48:13 PM cz.cas.lib.proarc.common.imports.audio.WaveImporter cons
ume
SEVERE: /home/proarc/.proarc/users/svetlym/import/1/MC-248539433021-01-01-00.mc.
wav
java.lang.IllegalStateException: Unsupported model: model:ndkaudiopage
        at cz.cas.lib.proarc.common.mods.ndk.NdkMapperFactory.lambda$get$1(NdkMa
pperFactory.java:80)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at cz.cas.lib.proarc.common.mods.ndk.NdkMapperFactory.get(NdkMapperFacto
ry.java:80)
        at cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetad
ataHandler.java:644)
        at cz.cas.lib.proarc.common.object.ndk.NdkAudioPlugin$1.setPage(NdkAudio
Plugin.java:161)
        at cz.cas.lib.proarc.common.imports.audio.WaveImporter.createMetadata(Wa
veImporter.java:154)
        at cz.cas.lib.proarc.common.imports.audio.WaveImporter.consume(WaveImpor
ter.java:85)
        at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSet
```

**Comment by svetlym** [comment]
Problém stále přetrvává a potřebovali bychom ho vyřešit, abychom mohli začít pracovat.

**Comment by SykoraLukas** [comment]
Na wiki byla doplněna dokumentace pro import Zvukových dokuementů.
Do `digobject.plugins=ndk`  je nutné přidat hodnotu `ndkAudio`

Mezi `import.profiles=profile.default, profile.oldprint`  je nutné přidat `profile.soundrecording_import`

Dále je nutné doplnit konfiguraci pro `profile.soundrecording_import` viz (konfigurace)[https://github.com/proarc/proarc/wiki/Konfigurace#zvuk-import].

Z vašich logů vidím, že import.profiles máte zakomentovaný. Prosím odkomentujte ho, a nastavte soubor `profile.soundrecording.cfg`

**Comment by svetlym** [comment]
Updatnul jsem proarc na verzi 3.5.13, proarc.cfg nastavil podle wiki a importované soubory jsem přejmenoval, aby měly stejné přípony jako v Národním muzeu.

Import spadnul s následující chybou:

```

/home/proarc/.proarc/users/svetlym/import/1/proarc_import/CO-248539433021-01-0001.foxml cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:520932b3-0793-40b3-b479-815314ed1113, file:/home/proarc/.proarc/users/svetlym/import/1/CO-248539433021-01-0001.xml at cz.cas.lib.proarc.common.ocr.AltoDatastream.importAlto(AltoDatastream.java:75) at cz.cas.lib.proarc.common.imports.TiffImporter.importOcr(TiffImporter.java:197) at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:108) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSet(SoundRecordingImport.java:121) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.consumeFileSets(SoundRecordingImport.java:102) at cz.cas.lib.proarc.common.imports.audio.SoundRecordingImport.start(SoundRecordingImport.java:89) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:212) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:183) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: org.xml.sax.SAXParseException; systemId: file:/home/proarc/.proarc/users/svetlym/import/1/CO-248539433021-01-0001.xml; lineNumber: 2; columnNumber: 263; cvc-elt.1.a: Cannot find the declaration of element 'alto'. at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source) at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source) at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source) at javax.xml.validation.Validator.validate(Validator.java:124) at cz.cas.lib.proarc.common.ocr.AltoDatastream.isAlto(AltoDatastream.java:87) at cz.cas.lib.proarc.common.ocr.AltoDatastream.importAlto(AltoDatastream.java:68) ... 13 more
```

Jestli tomu dobře rozumím, tak to padá na importu tohoto souboru:

[CO-248539433021-01-0001.zip](https://github.com/proarc/proarc/files/3858637/CO-248539433021-01-0001.zip)

Soubor je vygenerovaný stejným ABBY recognition serverem jako ALTO.xml pro všechny naše ostatní dokumenty.

Zkusil jsem v profile.soundrecording.cfg změnit `import.alto.file.version=3.0` na `import.alto.file.version=2.0` a nepomohlo to.

**Comment by SykoraLukas** [comment]
Momentálně jsem naimportoval váš soubor. V souboru profile.soundrecording.cfg je nutné změnit verzi alta. Zkoušeno s hodnotou 2.0 a 2.1 a oboje prošlo. S hodnotou 3.0 import neprojde

**Comment by svetlym** [comment]
Aha, ono je zřejmě třeba proarc restartovat, aby se projevila změna v konfiguraci. Mea culpa. Ještě jsem teda musel některé soubory přejmenovat podle toho, co chtěl Proarc, ale import pak prošel.

Výsledek mi ale nepřijde úplně správně:

![po_importu](https://user-images.githubusercontent.com/11628774/69348279-34384a80-0c76-11ea-9ab6-aabf4fd5b79e.png)

Wav bychom snad měli mít standardní, pouze vzorkovací frekvenci máme poloviční oproti tomu, co teď doporučuje Filip. S tím ale nic nenaděláme, už je to tak nahrané.


A pak ještě možná bude problém se strukturou. Naše vstupní soubory vypadají takhle:

```
CO-248539433021-01-0002.uc.jp2
CO-248539433021-01-0002.mc.jp2
CO-248539433021-01-0001.uc.jp2
CO-248539433021-01-0001.mc.jp2
CO-248539433021-01-0001.xml
CO-248539433021-01-0001.txt
CO-248539433021-01-0002.xml
CO-248539433021-01-0002.txt
CO-248539433021-01-0002.tif
CO-248539433021-01-0001.tif
MC-248539433021-01-02-01.wav
MC-248539433021-01-02-02.mp3
MC-248539433021-01-02-01.mp3
MC-248539433021-01-01-02.mp3
MC-248539433021-01-01-01.mp3
MC-248539433021-01-01-01.wav
```

Jestli tomu dobře rozumím, tak každému wavu odpovídá několik souborů mp3 - mám dojem, že se wavy rozřezávaly na jednotlivé stopy (nemám tu teď kolegu, který to dělal, takže si to nemůžu ověřit) a každá z nich se ukládala jako samostatný mp3 soubor. Počítá se vůbec s takovou možností?

**Comment by svetlym** [comment]
Import zvukových dokumentů jsme v MKP zprovoznili, zavírám issue.
